Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2021-11, with the labels that each got.

#878 Bugfix/33348 correcao log fluxo status
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_fluxo_status_homologacao.html
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: bug

#879 Hom - Atualização até 01/11/2021 às 15:45
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_fluxo_status_homologacao.html
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: bug

#903 Bugfix/sonar code injection
  sme_terceirizadas/logistica/api/validators.py
  sme_terceirizadas/logistica/api/viewsets.py
Labels: bug

#912 Feature/53092 de botao gerar protocolo
  sme_terceirizadas/relatorios/__tests__/test_relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial_protocolo.html
Labels: feature

#914 Hom - Atualização até 22/11/2021 às 12:10
  config/settings/base.py
  sme_terceirizadas/eol_servico/utils.py
  sme_terceirizadas/logistica/api/validators.py
  sme_terceirizadas/logistica/api/viewsets.py
  sme_terceirizadas/relatorios/__tests__/test_relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial_protocolo.html
Labels: bug, feature

#917 Feature/48279 ga kit lanche passeio dieta especial cadastro kit
  sme_terceirizadas/kit_lanche/__tests__/conftest.py
  sme_terceirizadas/kit_lanche/__tests__/test_serializers_create.py
  sme_terceirizadas/kit_lanche/__tests__/test_urls.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers_create.py
  sme_terceirizadas/kit_lanche/migrations/0010_solicitacaokitlancheavulsa_alunos_com_dieta_especial_participantes.py
  sme_terceirizadas/kit_lanche/models.py
Labels: feature

#918 HOM - Atualização até 24/11/2021 - 18:30
  sme_terceirizadas/kit_lanche/__tests__/conftest.py
  sme_terceirizadas/kit_lanche/__tests__/test_serializers_create.py
  sme_terceirizadas/kit_lanche/__tests__/test_urls.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers_create.py
  sme_terceirizadas/kit_lanche/migrations/0010_solicitacaokitlancheavulsa_alunos_com_dieta_especial_participantes.py
  sme_terceirizadas/kit_lanche/models.py
Labels: feature

#919 Fix: correção url dos anexos
  sme_terceirizadas/dieta_especial/api/serializers.py
Labels: bug

#920 Hom - Atualizado até 25/11 as 11:40
  sme_terceirizadas/dieta_especial/api/serializers.py
Labels: bug

#923 Feature/53176-GA-kit-lanche-passeio-exibição-alunos-com-dieta-especial
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
Labels: feature

#924 HOM - Atualização até 25/11/2021 - 17:10
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
Labels: feature

#925 Feature: adicionar permissões para o usuário joao_mesquita
  Jenkinsfile
Labels: feature

#926 Hom - Atualizado até 25/11 as 19:00
  Jenkinsfile
Labels: feature
