Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-10, with the labels that each got.

#1573 Feature/75028-PeD-melhoria-produtos-homologados-e-em-correção-para-dieta
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_utils.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/utils.py
Labels: enhancement, feature

#1598 Feature: listar produtos com reclamações em homologados
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#1604 Feature/75586-GA-relatorio-escola-kit-lanche-passeio-CEMEI
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/migrations/0022_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0023_solicitacoes.sql
Labels: enhancement, feature

#1606 Hom - Atualizado até 10/10/22 as 18:00
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/migrations/0022_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0023_solicitacoes.sql
Labels: enhancement, feature

#1621 Feature/75795-GA-relatorio-DRE-kit-lanche-passeio-CEMEI
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
Labels: enhancement, feature

#1622 Hom - Atualizado até 13/10/22 as 15:55
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
Labels: enhancement, feature

#1625 Hom - atualizado até 14/10 as 10:30
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1623 Feature/75561-GA-painel-solicitações--solicitação-inclusão-ETEC
  sme_terceirizadas/paineis_consolidados/migrations/0023_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0024_solicitacoes.sql
Labels: enhancement, feature

#1626 Hom - Atualizado até 14/10/22 as 11:15
  sme_terceirizadas/paineis_consolidados/migrations/0023_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0024_solicitacoes.sql
Labels: enhancement, feature

#1629 Feature/75801-kit-lanche-cemei-codae
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
Labels: enhancement, feature

#1630 Hom - Atualizado até 14/10/22 as 20:10
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
Labels: enhancement, feature

#1631 Feature/75561-GA-painel-solicitações--solicitação-inclusão-ETEC
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_continua.html
Labels: enhancement, feature

#1632 Hom - Atualizado até 14/10/22 as 21:30
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_continua.html
Labels: enhancement, feature

#1633 Feature/75039 relatorio produtos suspensos
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#1635 Fix: filtros de tipo em produtos suspensos
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1636 Hom atualizado 17/10 as 12h25
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1639 Fix: correção ao filtrar por data e tipo
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1640 Hom atualizado 17/10 as 18h00
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1641 Fix: ordenar dados por nome
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1642 Hom atualizado 18/10 as 11h40
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1643 Bugfix/75039 voltar para get
  sme_terceirizadas/dados_comuns/api/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1644 Hom atualizado 18/10 as 13h35
  sme_terceirizadas/dados_comuns/api/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1645 Fix: opcoes editais e testes
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1646 Hom atualizado 18/10 as 14h55
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1647 Fix: filtro de data suspensao
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1648 Hom atualizado 18/10 as 16h20
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1649 Hom atualizado 18/10 as 17h10
  config/urls.py
  sme_terceirizadas/conftest.py
  sme_terceirizadas/dados_comuns/api/serializers.py
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/logistica/__tests__/conftest.py
  sme_terceirizadas/logistica/__tests__/test_exporta_para_excel.py
  sme_terceirizadas/logistica/__tests__/test_guia/test_guia_endpoint.py
  sme_terceirizadas/logistica/__tests__/test_helpers.py
  sme_terceirizadas/logistica/__tests__/test_solicitacao/test_solicitacao_endpoint.py
  sme_terceirizadas/logistica/api/helpers.py
  sme_terceirizadas/logistica/api/services/exporta_para_excel.py
  sme_terceirizadas/paineis_consolidados/migrations/0022_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/migrations/0023_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0023_solicitacoes.sql
  sme_terceirizadas/paineis_consolidados/sql/0024_solicitacoes.sql
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/__tests__/test_utils.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/forms.py
  sme_terceirizadas/produto/utils.py
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_continua.html
  sme_terceirizadas/safi_servico/__init__.py
  sme_terceirizadas/safi_servico/__tests__/__init__.py
  sme_terceirizadas/safi_servico/__tests__/test_urls.py
  sme_terceirizadas/safi_servico/api/__init__.py
  sme_terceirizadas/safi_servico/api/viewsets.py
  sme_terceirizadas/safi_servico/urls.py
  sme_terceirizadas/safi_servico/utils.py
Labels: feature

#1656 Feature: validar existencia de solicitações no mesmo período e mês em alteração de cardapio
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/dados_comuns/validators.py
Labels: feature

#1659 Hom atualizado 24/10 as 11h00
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/dados_comuns/validators.py
Labels: feature

#1660 Feature/76462-PeD-tela-vincular-produtos-editais-incluir-campo-tipo-produto-edital-origem
  sme_terceirizadas/produto/api/viewsets.py
Labels: enhancement, feature

#1662 Hom - Atualizado até 25/10/22 as 11:45
  sme_terceirizadas/produto/api/viewsets.py
Labels: enhancement, feature

#1687 Feature/76797--tela-gerenciamento-de-email-busca-edicão-exclusão
  sme_terceirizadas/terceirizada/api/serializers/serializers.py
  sme_terceirizadas/terceirizada/api/viewsets.py
Labels: enhancement, feature

#1689 Hom - Atualizado até 28/10/22 as 12:45
  sme_terceirizadas/terceirizada/api/serializers/serializers.py
  sme_terceirizadas/terceirizada/api/viewsets.py
Labels: enhancement, feature
