Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-07, with the labels that each got.

#1330 Feature/64864 alteracao fluxo homologacao produto
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/__tests__/test_utils.py
  sme_terceirizadas/produto/api/filters.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/management/commands/unificar_homologacoes_antigas.py
  sme_terceirizadas/produto/migrations/0064_auto_20220630_0842.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/produto/utils.py
  sme_terceirizadas/relatorios/relatorios.py
Labels: feature, refactoring

#1339 HOM - Atualizada 01/07 às 16:20
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/__tests__/test_utils.py
  sme_terceirizadas/produto/api/filters.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/management/commands/unificar_homologacoes_antigas.py
  sme_terceirizadas/produto/migrations/0064_auto_20220630_0842.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/produto/utils.py
  sme_terceirizadas/relatorios/relatorios.py
Labels: feature, refactoring

#1348 Feature/67460-DE-incluir-disparo-de-emails-dietas-canceladas-para-contato-email-escola
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: feature

#1349 Hom - Atualizado até 05/07/22 as 17:15
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: feature

#1350 Feature/67753-GA-alterar-termo-merenda-seca-para-lanche-emergencial
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: feature

#1351 Hom - Atualizado até 06/07/22 as 10:20
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: feature

#1355 Feature/67460-DE-incluir-disparo-de-emails-dietas-canceladas-para-contato-email-escola
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: bug, feature

#1356 Hom - Atualizado até 07/07/22 as 18:45
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: bug, feature

#1377 Fix: flake8
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: bug

#1376 Feature: ordenação correta de reclamações
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: feature

#1378 Hom atualizado 15/07 as 12:20
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/constants.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0023_auto_20220714_0722.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/kit_lanche/api/validators.py
  sme_terceirizadas/kit_lanche/migrations/0012_auto_20220714_0817.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/perfil/__tests__/conftest.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
  sme_terceirizadas/produto/__tests__/test_utils.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/utils.py
Labels: feature

#1382 Bugfix/correcao sprint 57
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/migrations/0050_periodoescolar_posicao.py
  sme_terceirizadas/escola/migrations/0051_auto_20220718_0545.py
  sme_terceirizadas/escola/migrations/0052_auto_20220718_1810.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
Labels: bug

#1383 HOM - Atualizado até 19/07 às 16:50
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/migrations/0050_periodoescolar_posicao.py
  sme_terceirizadas/escola/migrations/0051_auto_20220718_0545.py
  sme_terceirizadas/escola/migrations/0052_auto_20220718_1810.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
Labels: bug

#1387 Feature/69226-DE-técnica-melhoria-nos-cadastros-de-alergias-intolerâncias
  setup.cfg
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/dieta_especial/management/commands/corrige_alergias_intolerancias_duplicadas.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: feature

#1390 Hom - Atualizado até 20/07/22 as 16:00
  setup.cfg
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/dieta_especial/management/commands/corrige_alergias_intolerancias_duplicadas.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/relatorio_situacao_produto.scss
  sme_terceirizadas/relatorios/templates/relatorio_produtos_situacao.html
Labels: feature

#1395 Fix: impedir a inativação dos períodos manuais de CEU GESTAO
  sme_terceirizadas/cardapio/tasks.py
Labels: bug

#1401 Feature/69541 ativar inativar produtos editais
  sme_terceirizadas/cardapio/tasks.py
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0065_produto_editais.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/produto/urls.py
Labels: feature

#1397 Feature/68883-PeD-técnica-otimização-telas-produtos
  sme_terceirizadas/produto/api/viewsets.py
Labels: enhancement, feature

#1407 Hom - Atualizado até 28/07/22 as 13:50
  sme_terceirizadas/produto/api/viewsets.py
Labels: enhancement, feature

#1413 Bugfix/69541 correcao modelagem
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0066_auto_20220729_0110.py
  sme_terceirizadas/produto/migrations/0067_produtoedital_ativo.py
  sme_terceirizadas/produto/migrations/0068_auto_20220729_0455.py
  sme_terceirizadas/produto/models.py
Labels: bug

#1415 HOM - Atualizada até 29/07 às 15:00
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0066_auto_20220729_0110.py
  sme_terceirizadas/produto/migrations/0067_produtoedital_ativo.py
  sme_terceirizadas/produto/migrations/0068_auto_20220729_0455.py
  sme_terceirizadas/produto/models.py
Labels: bug
