Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-12, with the labels that each got.

#1805 Feature/78920 resultado da grid solicitacoes ga
  config/settings/base.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/migrations/0028_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/sql/0029_solicitacoes.sql
Labels: feature

#1807 Feature: filtrar por terceirizada
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: bug

#1808 Hom atualizado 01/12 as 18h20
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: bug

#1809 Feature/70415-MI-tela-lançamento-de-dietas
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/fixtures/categorias_de_medicao.yaml
Labels: feature

#1810 Hom - Atualizado até 01/12/22 as 21:15
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/fixtures/categorias_de_medicao.yaml
Labels: feature

#1834 Hom - Atualizado até 08/12/22 as 12:45
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
Labels: enhancement, feature

#1835 Feature/79846-GA-impressão-pdf-inclusão-cemei
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
Labels: enhancement, feature

#1836 Hom - Atualizado até 08/12/22 as 15:20
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
Labels: enhancement

#1838 Feature/79846-GA-impressão-pdf-inclusão-cemei
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
Labels: enhancement

#1840 Hom - Atualizado até 08/12/22 as 16:50
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
Labels: enhancement

#1844 Feature/79846-GA-impressão-pdf-inclusão-cemei
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#1845 Hom - Atualizado até 09/12/22 as 09:40
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#1832 Feature/79713-GA-alterar-nomenclatura-solicitação-de-alteração-cei-no-dashboard
  sme_terceirizadas/paineis_consolidados/migrations/0029_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0030_solicitacoes.sql
Labels: enhancement, feature

#1846 Hom - Atualizado até 09/12/22 as 09:55
  sme_terceirizadas/paineis_consolidados/migrations/0029_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0030_solicitacoes.sql
Labels: enhancement, feature

#1843 Feature/79037 expansor para relatorios inclusao
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/urls.py
Labels: feature

#1853 Hom - atualizado até 12/12 as 14:45
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/urls.py
Labels: feature

#1854 Fix: mudar nome do status para recebidas
  sme_terceirizadas/paineis_consolidados/__tests__/test_url.py
  sme_terceirizadas/paineis_consolidados/api/constants.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
Labels: bug

#1857 Fix: numero de alunos
  sme_terceirizadas/paineis_consolidados/api/serializers.py
Labels: bug

#1862 Hom - Atualizado até 12/12/22 as 16:00
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/utils.py
Labels: enhancement, feature

#1871 Feature/80349 relatorio solicitacao kit lanche
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/paineis_consolidados/models.py
Labels: feature

#1872 Hom atualizado 14/12 as 16h50
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/paineis_consolidados/models.py
Labels: feature

#1916 Feature/78928 pdf relatorio solicitacoes ga inclusoes
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/tasks.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacoes_alimentacao.scss
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
  sme_terceirizadas/relatorios/templates/relatorio_solicitacoes_alimentacao.html
Labels: feature

#1918 Feature/76113-DE-usuários-com-solicitações-dietas-recebidas-abertas-tempo-real
  Pipfile
  config/asgi.py
  config/settings/base.py
  sme_terceirizadas/dados_comuns/api/serializers.py
  sme_terceirizadas/dados_comuns/api/viewsets.py
  sme_terceirizadas/dados_comuns/apps.py
  sme_terceirizadas/dados_comuns/consumers.py
  sme_terceirizadas/dados_comuns/migrations/0065_solicitacaoaberta.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/signals.py
  sme_terceirizadas/dados_comuns/urls.py
Labels: feature

#1924 Feature/81332 ga pdf solicitacoes alteracao cardapio
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
  sme_terceirizadas/relatorios/templates/relatorio_solicitacoes_alimentacao.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: feature

#1929 Hom - Atualizado até 28/12/22 as 10:45
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
  sme_terceirizadas/relatorios/templates/relatorio_solicitacoes_alimentacao.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: feature

#1936 Fix: data cancelamento, autorização e negação
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
Labels: bug

#1937 Hom atualizado 28/12 as 16h35
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
Labels: bug

#1938 Fix: label data
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
  sme_terceirizadas/relatorios/templates/bloco_inversao_dia_cardapio.html
  sme_terceirizadas/relatorios/templates/bloco_suspensao_alimentacao.html
  sme_terceirizadas/relatorios/templates/bloco_suspensao_alimentacao_cei.html
  sme_terceirizadas/relatorios/templates/relatorio_solicitacoes_alimentacao.html
Labels: bug

#1941 Feature/81334 relatorio pdf solicitacoes kit lanche
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cei.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_unificado.html
  sme_terceirizadas/relatorios/templates/relatorio_solicitacoes_alimentacao.html
Labels: feature

#1942 Hom atualizado 28/12 as 20h30
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cei.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_unificado.html
  sme_terceirizadas/relatorios/templates/relatorio_solicitacoes_alimentacao.html
Labels: feature

#1943 Fix: typo
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/relatorios/templates/relatorio_solicitacoes_alimentacao.html
Labels: bug

#1950 Fix/GA-correções-relatórios-solicitações-alimentações
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/relatorios/templates/bloco_inversao_dia_cardapio.html
  sme_terceirizadas/relatorios/templates/relatorio_solicitacoes_alimentacao.html
Labels: bug

#1951 Hom atualizado 30/12 as 17h30
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inversao_dia_cardapio.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cemei.html
  sme_terceirizadas/relatorios/templates/relatorio_solicitacoes_alimentacao.html
Labels: bug
