Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-05, with the labels that each got.

#1201 Feature/62896 cadastro tipos alimentacao
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
Labels: feature

#1202 Hom - Atualizado até 02/05/22 as 08:40
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
Labels: feature

#1203 Prod - Atualizado até 02/05/2022 as 16:35
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0056_auto_20220421_1551.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/templates/fluxo_codae_autoriza_ou_nega_dieta.html
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0018_auto_20220426_1325.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/relatorios/constants.py
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: bug, feature

#1207 Atualizacao da modelagem de alteracao de cardapio CEI
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/migrations/0027_auto_20220504_1610.py
  sme_terceirizadas/cardapio/models.py
Labels: refactoring

#1209 Feature/62415-PeD-melhoria-desempenho-painel-gestão-produtos
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature, refactoring

#1211 Hom - Atualizado até 06/05/22 as 18:25
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/migrations/0027_auto_20220504_1610.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/logistica/management/commands/atualiza_data_entrega_guias.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature, refactoring

#1218 HOM - Atualizada 16/05 às 10:50
  Pipfile
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_models.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/validators.py
  sme_terceirizadas/cardapio/migrations/0029_auto_20220512_0428.py
  sme_terceirizadas/cardapio/models.py
Labels: feature

#1220 Hom - Atualizado até 16/05/22 as 12:50
  sme_terceirizadas/dieta_especial/api/filters.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/forms.py
Labels: feature

#1228 Feature/63529-DE-resultado-da-busca-relatórios-dieta-especial-terceirizadas
  sme_terceirizadas/dieta_especial/api/serializers.py
Labels: feature

#1229 Hom - Atualizado até 17/05/22 as 15:05
  sme_terceirizadas/dieta_especial/api/serializers.py
Labels: feature

#1232 Feature/63534 de relatorio pdf terceirizada
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/relatorio_dietas_especiais_terceirizada.scss
  sme_terceirizadas/relatorios/templates/cabecalho_rodape_relatorio_dietas_terceirizada.html
  sme_terceirizadas/relatorios/templates/relatorio_dietas_especiais_terceirizada.html
Labels: feature

#1233 HOM - Atualizada 18/05 às 09:35
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/relatorio_dietas_especiais_terceirizada.scss
  sme_terceirizadas/relatorios/templates/cabecalho_rodape_relatorio_dietas_terceirizada.html
  sme_terceirizadas/relatorios/templates/relatorio_dietas_especiais_terceirizada.html
Labels: feature

#1234 Fix: algumas dietas estão apenas com nome do protocolo salvo
  sme_terceirizadas/dieta_especial/api/viewsets.py
Labels: bug

#1235 HOM - Atualizada 18/05 às 10:05
  sme_terceirizadas/dieta_especial/api/viewsets.py
Labels: bug

#1236 Feature/63650-DE-disparo-email-dietas-canceladas-manualmente-automaticamente
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/templates/email/email_dieta_cancelada_automaticamente_terceirizada_escola_destino.html
  sme_terceirizadas/dieta_especial/utils.py
Labels: feature

#1238 Feature/63650-DE-disparo-email-dietas-canceladas-manualmente-automaticamente
  sme_terceirizadas/dieta_especial/utils.py
Labels: feature

#1239 Feature/63650-DE-disparo-email-dietas-canceladas-manualmente-automaticamente
  sme_terceirizadas/dieta_especial/api/viewsets.py
Labels: feature

#1241 Prod - Atualizado até 18/05/2022 as 16:40
  Dockerfile
  Pipfile
  Pipfile.lock
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_models.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/admin.py
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/validators.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/fixtures/motivos_dre_nao_valida.yaml
  sme_terceirizadas/cardapio/migrations/0027_auto_20220504_1610.py
  sme_terceirizadas/cardapio/migrations/0028_motivodrenaovalida.py
  sme_terceirizadas/cardapio/migrations/0029_auto_20220512_0428.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/cardapio/urls.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dieta_especial/api/filters.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/forms.py
  sme_terceirizadas/dieta_especial/templates/email/email_dieta_cancelada_automaticamente_terceirizada_escola_destino.html
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_urls.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0019_inclusaoalimentacaonormal_cancelado.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0020_inclusaoalimentacaonormal_cancelado_justificativa.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/logistica/api/soup/models.py
  sme_terceirizadas/logistica/management/commands/atualiza_data_entrega_guias.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/relatorio_dietas_especiais_terceirizada.scss
  sme_terceirizadas/relatorios/templates/bloco_historico_cancelamento_inclusao.html
  sme_terceirizadas/relatorios/templates/cabecalho_rodape_relatorio_dietas_terceirizada.html
  sme_terceirizadas/relatorios/templates/relatorio_dietas_especiais_terceirizada.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_normal.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: bug, feature

#1245 Feature/65355 deb tec request too long
  sme_terceirizadas/logistica/api/soup/views.py
Labels: technical debit

#1244 Feature: ordenar por nome do kit lanche
  sme_terceirizadas/kit_lanche/api/viewsets.py
Labels: feature

#1251 Fix/31506-GA-erro-ao-abrir-rascunho-alteração-cardápio-e-kit-lanche
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
Labels: bug

#1252 Hom - Atualizado até 30/05/22 as 17:45
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
Labels: bug
