Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-11, with the labels that each got.

#1695 Prod - Atualizado até 01/10/2022 as 18:00
  sme_terceirizadas/cardapio/admin.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/migrations/0038_motivoalteracaocardapio_ativo.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/validators.py
  sme_terceirizadas/eol_servico/utils.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/constants.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/kit_lanche/__tests__/conftest.py
  sme_terceirizadas/kit_lanche/__tests__/test_models.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/paineis_consolidados/api/filters.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/kit_lanche_cemei.scss
  sme_terceirizadas/relatorios/templates/bloco_cabecalho_solicitacao_partindo_escola_completo.html
  sme_terceirizadas/relatorios/templates/bloco_historico_cancelamento.html
  sme_terceirizadas/relatorios/templates/bloco_observacoes.html
  sme_terceirizadas/relatorios/templates/cabecalho_rodape_solicitacao.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_cemei.html
  sme_terceirizadas/relatorios/templatetags/index.py
  sme_terceirizadas/terceirizada/__tests__/conftest.py
  sme_terceirizadas/terceirizada/__tests__/test_models.py
  sme_terceirizadas/terceirizada/__tests__/test_serializers.py
  sme_terceirizadas/terceirizada/__tests__/test_url.py
  sme_terceirizadas/terceirizada/admin.py
  sme_terceirizadas/terceirizada/api/filters.py
  sme_terceirizadas/terceirizada/api/serializers/serializers.py
  sme_terceirizadas/terceirizada/api/viewsets.py
  sme_terceirizadas/terceirizada/migrations/0008_emailterceirizadapormodulo_modulo.py
  sme_terceirizadas/terceirizada/models.py
  sme_terceirizadas/terceirizada/urls.py
  sme_terceirizadas/terceirizada/utils.py
Labels: enhancement, feature

#1696 Feature/77600-GA-inclusão-alimentação-cemei-relatório-dre
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
Labels: feature

#1701 Hom - Atualizado até 03/11/22 as 13:25
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
Labels: feature

#1702 Feature/77607-GA-inclusão-alimentação-cemei-relatório-codae
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/managers.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/kit_lanche/managers/__init__.py
  sme_terceirizadas/kit_lanche/managers/kit_lanche_cemei_manager.py
  sme_terceirizadas/kit_lanche/models.py
Labels: enhancement, feature

#1703 Hom - Atualizado até 03/11/22 as 14:20
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/managers.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/kit_lanche/managers/__init__.py
  sme_terceirizadas/kit_lanche/managers/kit_lanche_cemei_manager.py
  sme_terceirizadas/kit_lanche/models.py
Labels: enhancement, feature

#1704 Feature/77608-GA-inclusão-alimentação-cemei-relatório-terceirizadas
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
Labels: enhancement, feature

#1706 Hom - Atualizado até 03/11/22 as 17:00
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
Labels: enhancement, feature

#1705 Feature/76112 remover tipos de alimentacao de solicitacoes cei
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/constants.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0026_quantidadedealunosporfaixaetariadainclusaodealimentacaodacei_periodo.py
  sme_terceirizadas/inclusao_alimentacao/models.py
Labels: feature

#1707 Hom atualizado 03/11 as 18h10
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/constants.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0026_quantidadedealunosporfaixaetariadainclusaodealimentacaodacei_periodo.py
  sme_terceirizadas/inclusao_alimentacao/models.py
Labels: feature

#1708 Feature/77867-GA-alteração-tipo-alimentação-cemei-relatório-dre
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/managers/alteracao_cardapio_manager.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
Labels: enhancement, feature

#1709 Hom - Atualizado até 04/11/22 as 09:40
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/managers/alteracao_cardapio_manager.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
Labels: enhancement, feature

#1710 Feature/77875-GA-alteração-tipo-alimentação-cemei-relatório-codae
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/models.py
Labels: enhancement, feature

#1711 Hom - Atualizado até 04/11/22 as 11:45
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/models.py
Labels: enhancement, feature

#1714 Hom - Atualizado até 04/11/22 as 12:20
  sme_terceirizadas/cardapio/api/viewsets.py
Labels: feature

#1718 Feature/77593-PeD-alterar-visualização-dos-campos-da-ficha-identificação-do-produto
  sme_terceirizadas/relatorios/templates/ficha_identificacao_produto.html
Labels: enhancement

#1723 Hom - Atualizado até 07/11/22 as 12:55
  sme_terceirizadas/relatorios/templates/ficha_identificacao_produto.html
Labels: enhancement

#1734 Fix: modelagem deve permitir criar solicitações sem passar o período
  sme_terceirizadas/inclusao_alimentacao/migrations/0027_auto_20221104_2024.py
  sme_terceirizadas/inclusao_alimentacao/models.py
Labels: bug

#1735 Hom - Atualizado até 09/11/22 as 09:45
  sme_terceirizadas/inclusao_alimentacao/migrations/0027_auto_20221104_2024.py
  sme_terceirizadas/inclusao_alimentacao/models.py
Labels: bug

#1749 Feature: sql e migração para exibir solicitações de alteração de cardápio CEMEI
  sme_terceirizadas/paineis_consolidados/migrations/0025_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0026_solicitacoes.sql
Labels: feature

#1750 HOM - Atualizada até 11/11 às 14:40
  sme_terceirizadas/paineis_consolidados/migrations/0025_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0026_solicitacoes.sql
Labels: feature

#1727 Feature/78295 relatorio inclusao alimentacao cei
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/conftest.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_urls.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/novo_solicitacao_inclusao_alimentacao_cei.html
Labels: feature

#1755 HOM - Atualizado até 11/11 às 16:40
  Jenkinsfile
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/conftest.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_urls.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/novo_solicitacao_inclusao_alimentacao_cei.html
Labels: feature

#1785 Feature/79479 ga dt popular matriculados no dia
  sme_terceirizadas/cardapio/management/commands/__init__.py
  sme_terceirizadas/cardapio/management/commands/substituicao_atualiza_matriculados_no_dia.py
  sme_terceirizadas/cardapio/migrations/0040_auto_20221121_1543.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/management/commands/__init__.py
  sme_terceirizadas/inclusao_alimentacao/management/commands/inclusao_atualiza_matriculados_no_dia.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0028_auto_20221121_1543.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/kit_lanche/management/commands/kit_lanche_atualiza_matriculados_no_dia.py
  sme_terceirizadas/kit_lanche/migrations/0016_auto_20221125_1057.py
  sme_terceirizadas/kit_lanche/models.py
Labels: feature

#1792 Bugfix/78679 - resolve bug transferencia de lote
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/terceirizada/__tests__/conftest.py
  sme_terceirizadas/terceirizada/__tests__/test_url.py
Labels: bug
