Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-04, with the labels that each got.

#1162 Hom - Atualizado até 01/04/22 as 11:15 (homolog > homolog-r2)
  .github/workflows/deploy-dev-pipecache.yml
  config/settings/local.py
  setup.cfg
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/dados_comuns/__tests__/conftest.py
  sme_terceirizadas/dados_comuns/__tests__/test_models.py
  sme_terceirizadas/dados_comuns/__tests__/test_urls.py
  sme_terceirizadas/dados_comuns/admin.py
  sme_terceirizadas/dados_comuns/api/filters.py
  sme_terceirizadas/dados_comuns/api/serializers.py
  sme_terceirizadas/dados_comuns/api/viewsets.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0054_centraldedownload.py
  sme_terceirizadas/dados_comuns/migrations/0055_auto_20220324_1238.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/templates/logistica_distribuidor_confirma_cancelamento.html
  sme_terceirizadas/dados_comuns/templates/logistica_notificacao_confirma_cancelamento_distribuidor.html
  sme_terceirizadas/dados_comuns/urls.py
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/eol_servico/utils.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/kit_lanche/__tests__/conftest.py
  sme_terceirizadas/kit_lanche/__tests__/test_serializers_create.py
  sme_terceirizadas/kit_lanche/__tests__/test_urls.py
  sme_terceirizadas/logistica/api/viewsets.py
  sme_terceirizadas/logistica/tasks.py
  sme_terceirizadas/perfil/__tests__/conftest.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/__tests__/test_utils.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial_protocolo.html
  sme_terceirizadas/relatorios/utils.py
Labels: feature

#1163 Prod - Atualizado até 04/04/2022 as 17:00
  .github/workflows/deploy-dev-pipecache.yml
  config/settings/local.py
  setup.cfg
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/dados_comuns/__tests__/conftest.py
  sme_terceirizadas/dados_comuns/__tests__/test_models.py
  sme_terceirizadas/dados_comuns/__tests__/test_urls.py
  sme_terceirizadas/dados_comuns/admin.py
  sme_terceirizadas/dados_comuns/api/filters.py
  sme_terceirizadas/dados_comuns/api/serializers.py
  sme_terceirizadas/dados_comuns/api/viewsets.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0054_centraldedownload.py
  sme_terceirizadas/dados_comuns/migrations/0055_auto_20220324_1238.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/templates/logistica_distribuidor_confirma_cancelamento.html
  sme_terceirizadas/dados_comuns/templates/logistica_notificacao_confirma_cancelamento_distribuidor.html
  sme_terceirizadas/dados_comuns/urls.py
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/eol_servico/utils.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/kit_lanche/__tests__/conftest.py
  sme_terceirizadas/kit_lanche/__tests__/test_serializers_create.py
  sme_terceirizadas/kit_lanche/__tests__/test_urls.py
  sme_terceirizadas/logistica/api/viewsets.py
  sme_terceirizadas/logistica/tasks.py
  sme_terceirizadas/perfil/__tests__/conftest.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/__tests__/test_utils.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial_protocolo.html
  sme_terceirizadas/relatorios/utils.py
Labels: feature

#1164 Hotfix/PeD-garantir-ordenação-de-logs
  sme_terceirizadas/dados_comuns/behaviors.py
Labels: bug

#1165 Prod - Atualizado até 04/04/2022 as 18:30
  sme_terceirizadas/dados_comuns/behaviors.py
Labels: bug

#1166 Hom - Atualizado até 04/04/22 as 19:55 (hotfix -- master > homolog)
  sme_terceirizadas/dados_comuns/behaviors.py
Labels: bug

#1167 Dev - Atualizado até 04/04/22 as 17:45 (hotfix -- homolog > development)
  sme_terceirizadas/dados_comuns/behaviors.py
Labels: bug

#1168 Feature: salvar justificativa da necação CODAE.
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
Labels: feature

#1169 Hom - Atualizado até 06/04/22 as 17:30
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
Labels: feature

#1170 Feature/57922 alteracao modelagem suspensao alimentacao
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_models.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/migrations/0023_vinculotipoalimentacaocomperiodoescolaretipounidadeescolar_tipos_alimentacao.py
  sme_terceirizadas/cardapio/migrations/0024_auto_20220408_1529.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: feature

#1172 Feature/57922 alteracao modelagem inclusao alimentacao
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/conftest.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0017_auto_20220411_1137.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/lancamento_inicial/utils.py
Labels: feature, refactoring

#1173 Feature/62343 gestao cancelamento requisicoes
  docs/Fluxo solicitação de cancelamento partindo do papa.png
  sme_terceirizadas/logistica/__tests__/conftest.py
  sme_terceirizadas/logistica/__tests__/test_solicitacao/test_model.py
  sme_terceirizadas/logistica/admin.py
  sme_terceirizadas/logistica/api/soup/models.py
  sme_terceirizadas/logistica/migrations/0044_logsolicitacaodecancelamentopelopapa.py
  sme_terceirizadas/logistica/models/__init__.py
  sme_terceirizadas/logistica/models/solicitacao.py
  sme_terceirizadas/logistica/services.py
Labels: feature

#1177 Hom - Atualizado até 14/04/22 as 18:10
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
Labels: bug

#1178 Feature/57922 alteracao modelagem alteracao cardapio
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_serializers_create.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/admin.py
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/validators.py
  sme_terceirizadas/cardapio/migrations/0025_auto_20220414_1325.py
  sme_terceirizadas/cardapio/migrations/0026_auto_20220414_1638.py
  sme_terceirizadas/cardapio/models.py
Labels: feature, refactoring

#1171 Feature/57922 modelagem combos alimentacao
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_models.py
  sme_terceirizadas/cardapio/__tests__/test_serializers_create.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/admin.py
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/validators.py
  sme_terceirizadas/cardapio/migrations/0023_vinculotipoalimentacaocomperiodoescolaretipounidadeescolar_tipos_alimentacao.py
  sme_terceirizadas/cardapio/migrations/0024_auto_20220408_1529.py
  sme_terceirizadas/cardapio/migrations/0025_auto_20220414_1325.py
  sme_terceirizadas/cardapio/migrations/0026_auto_20220414_1638.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/conftest.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0017_auto_20220411_1137.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/lancamento_inicial/utils.py
Labels: feature, refactoring

#1179 Hom - Atualizado até 19/04/22 as 09:30
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_models.py
  sme_terceirizadas/cardapio/__tests__/test_serializers_create.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/admin.py
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/validators.py
  sme_terceirizadas/cardapio/migrations/0023_vinculotipoalimentacaocomperiodoescolaretipounidadeescolar_tipos_alimentacao.py
  sme_terceirizadas/cardapio/migrations/0024_auto_20220408_1529.py
  sme_terceirizadas/cardapio/migrations/0025_auto_20220414_1325.py
  sme_terceirizadas/cardapio/migrations/0026_auto_20220414_1638.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/conftest.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0017_auto_20220411_1137.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/lancamento_inicial/utils.py
Labels: feature, refactoring

#1185 feature/62612-PeD-melhoria-área-de-pesquisa-dos-cards
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: feature

#1186 Hom - Atualizado até 21/04/22 as 19:15
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: feature

#1190 Feature: rota para retornar apenas escolas TERC TOTAL
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
Labels: feature

#1192 Alteracao na modelagem de inclusao de alimentacao CEI
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0018_auto_20220426_1325.py
  sme_terceirizadas/inclusao_alimentacao/models.py
Labels: refactoring

#1197 Hotfix/62027-PeD-ajuste-logs-homologacoes-de-produto-antigas
  sme_terceirizadas/produto/management/commands/ajuste_logs_antigos.py
Labels: bug

#1198 Prod - Atualizado até 29/04/2022 as 17:35 (hotfix)
  sme_terceirizadas/produto/management/commands/ajuste_logs_antigos.py
Labels: bug

#1200 Dev - Atualizado até 29/04/2022 as 18:25 (hotfix -- homolog > development)
  README.md
  sme_terceirizadas/produto/management/commands/ajuste_logs_antigos.py
Labels: bug, feature
