Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-09, with the labels that each got.

#1511 Feature/70695-MI-tela-de-lancamento-de-alimentacao-pt1
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0004_categoriamedicao_medicao_valormedicao.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/urls.py
Labels: feature

#1512 Hom - Atualizado até 31/08/22 as 22:40
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0004_categoriamedicao_medicao_valormedicao.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/urls.py
Labels: feature

#1513 Feature/70398 relatorio suspensao cei
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/constants.py
Labels: feature

#1514 Hom - Atualizado até 01/09/22 as 12:20
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/constants.py
Labels: feature

#1515 Prod - Atualizado até 05/09/2022 as 10:00
  .github/workflows/check-status.yml
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/serializers_create.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/migrations/0048_protocolopadraodietaespecial_editais.py
  sme_terceirizadas/dieta_especial/models.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0004_categoriamedicao_medicao_valormedicao.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/urls.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/forms.py
  sme_terceirizadas/produto/utils.py
  sme_terceirizadas/relatorios/static/css/_variaveis.scss
  sme_terceirizadas/relatorios/static/css/cabecalho.scss
  sme_terceirizadas/relatorios/static/css/produtos_terceirizada.scss
  sme_terceirizadas/relatorios/templates/homologacao_marcas_por_produto.html
  sme_terceirizadas/relatorios/templates/relatorio_produtos_por_terceirizada.html
Labels: bug, enhancement, feature

#1516 Feature: retorna protocolos com base nos editais vinculados a escola da solicitação
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
Labels: feature

#1518 Hom - Atualizado até 06/09/22 as 15:45
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/dados_comuns/migrations/0059_auto_20220906_1423.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/escola/migrations/0053_periodoescolar_tipo_turno.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/conftest.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_urls.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0025_diasmotivosinclusaodealimentacaocemei_inclusaodealimentacaocemei_quantidadedealunosemeiinclusaodeali.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/inclusao_alimentacao/urls.py
  sme_terceirizadas/perfil/__tests__/conftest.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
Labels: feature

#1519 Feature/71891-MI-tela-lançamento-número-de-matriculados
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/urls.py
Labels: feature

#1523 Feature/71891-MI-tela-lançamento-número-de-matriculados
  sme_terceirizadas/escola/utils.py
Labels: feature

#1524 Hom - Atualizado até 09/09/22 as 18:30
  sme_terceirizadas/escola/utils.py
Labels: feature

#1526 Feature: solicitacao de inversao de cardapio CEMEI
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/migrations/0034_inversaocardapio_alunos_da_cemei.py
  sme_terceirizadas/cardapio/migrations/0035_auto_20220912_1019.py
  sme_terceirizadas/cardapio/models.py
Labels: feature

#1527 HOM - Atualizado até 12/09
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/migrations/0034_inversaocardapio_alunos_da_cemei.py
  sme_terceirizadas/cardapio/migrations/0035_auto_20220912_1019.py
  sme_terceirizadas/cardapio/models.py
Labels: feature

#1532 Feature/71892-MI-tela-lancamento-validações-frequência
  sme_terceirizadas/paineis_consolidados/migrations/0020_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/sql/0021_solicitacoes.sql
Labels: enhancement, feature

#1533 Hom - Atualizado até 14/09/22 as 17:30
  sme_terceirizadas/paineis_consolidados/migrations/0020_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/sql/0021_solicitacoes.sql
Labels: enhancement, feature

#1535 Feature/73034-GA-solicitação-suspensão-CEMEI
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/migrations/0036_quantidadeporperiodosuspensaoalimentacao_alunos_cei_ou_emei.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
Labels: enhancement, feature

#1536 Hom - Atualizado até 17/09/22 as 13:30
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/migrations/0036_quantidadeporperiodosuspensaoalimentacao_alunos_cei_ou_emei.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
Labels: enhancement, feature

#1545 Prod - Atualizado até 21/09/2022 as 14:55
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/migrations/0034_inversaocardapio_alunos_da_cemei.py
  sme_terceirizadas/cardapio/migrations/0035_auto_20220912_1019.py
  sme_terceirizadas/cardapio/migrations/0036_quantidadeporperiodosuspensaoalimentacao_alunos_cei_ou_emei.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0059_auto_20220906_1423.py
  sme_terceirizadas/dados_comuns/migrations/0060_auto_20220915_0906.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/serializers_create.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/escola/migrations/0053_periodoescolar_tipo_turno.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/urls.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/conftest.py
  sme_terceirizadas/inclusao_alimentacao/__tests__/test_urls.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0025_diasmotivosinclusaodealimentacaocemei_inclusaodealimentacaocemei_quantidadedealunosemeiinclusaodeali.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/inclusao_alimentacao/urls.py
  sme_terceirizadas/kit_lanche/__tests__/conftest.py
  sme_terceirizadas/kit_lanche/__tests__/test_urls.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers_create.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/kit_lanche/migrations/0014_faixasquantidadeskitlancheceidacemei_solicitacaokitlancheceidacemei_solicitacaokitlanchecemei_solici.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/kit_lanche/urls.py
  sme_terceirizadas/logistica/services.py
  sme_terceirizadas/paineis_consolidados/migrations/0020_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/sql/0021_solicitacoes.sql
  sme_terceirizadas/perfil/__tests__/conftest.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
Labels: bug, enhancement, feature

#1544 Feature: criar alteração de cardápio CEMEI
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/cardapio/migrations/0037_alteracaocardapiocemei_faixaetariasubstituicaoalimentacaocemeicei_substituicaoalimentacaonoperiodoes.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/cardapio/urls.py
Labels: feature

#1549 Fix: usar serializer mais simples pois não há necessidade de trazer muitas informações da escola
  sme_terceirizadas/escola/api/serializers.py
Labels: bug

#1550 Hom atualizado 23/09 as 10h30
  sme_terceirizadas/escola/api/serializers.py
Labels: bug

#1553 Feature/74098-PeD-impressão-pdf-ficha-identificação-produto
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/relatorios/static/css/cabecalho.scss
  sme_terceirizadas/relatorios/static/css/override_relatorio.scss
  sme_terceirizadas/relatorios/templates/cabecalho_rodape_ficha_identificacao_produto.html
  sme_terceirizadas/relatorios/templates/ficha_identificacao_produto.html
Labels: feature

#1554 Hom - Atualizado até 23/09/22 as 13:45
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/relatorios/static/css/cabecalho.scss
  sme_terceirizadas/relatorios/static/css/override_relatorio.scss
  sme_terceirizadas/relatorios/templates/cabecalho_rodape_ficha_identificacao_produto.html
  sme_terceirizadas/relatorios/templates/ficha_identificacao_produto.html
Labels: feature

#1559 Feature/72225-MI-upload-arquivos-de-ocorrências
  sme_terceirizadas/dados_comuns/__tests__/conftest.py
  sme_terceirizadas/dados_comuns/__tests__/test_validators.py
  sme_terceirizadas/dados_comuns/validators.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_models.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0005_auto_20220928_1333.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#1572 Hom - Atualizado até 30/09/22 as 10:10
  sme_terceirizadas/dados_comuns/__tests__/conftest.py
  sme_terceirizadas/dados_comuns/__tests__/test_validators.py
  sme_terceirizadas/dados_comuns/validators.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_models.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0005_auto_20220928_1333.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature
