Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-08, with the labels that each got.

#1420 Feature/69346-PeD-seleção-de-editais
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/terceirizada/api/serializers/serializers.py
Labels: feature

#1421 Feature/66586 exibir produtos vinculados a editais
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0069_auto_20220801_0708.py
  sme_terceirizadas/produto/models.py
Labels: feature

#1422 Hom - Atualizado até 01/08/22 as 09:00
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0069_auto_20220801_0708.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/terceirizada/api/serializers/serializers.py
Labels: feature

#1429 Hotfix/71161-DE-solicitações-alteração-ue
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#1430 Prod - Atualizado até 02/08 as 19:10
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#1431 Hom - Atualizado até 03/08 as 15:55
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#1432 Dev - Atualizado até 03/08 as 16:00
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#1433 Feature/69543 vincular editais
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0070_auto_20220803_0134.py
  sme_terceirizadas/produto/migrations/0071_auto_20220804_1133.py
  sme_terceirizadas/produto/migrations/0072_auto_20220804_1207.py
  sme_terceirizadas/produto/models.py
Labels: feature

#1434 Hom - Atualizado até 04/08 as 14:25
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0070_auto_20220803_0134.py
  sme_terceirizadas/produto/migrations/0071_auto_20220804_1133.py
  sme_terceirizadas/produto/migrations/0072_auto_20220804_1207.py
  sme_terceirizadas/produto/models.py
Labels: feature

#1435 Prod - Atualizado até 05/08/2022 as 10:10
  setup.cfg
  sme_terceirizadas/cardapio/migrations/0031_suspensaoalimentacaodacei_terceirizada_conferiu_gestao.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/dados_comuns/templates/logistica_notificacao_escola_aviso_reposicao.html
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/dieta_especial/management/commands/corrige_alergias_intolerancias_duplicadas.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/tasks.py
  sme_terceirizadas/logistica/__tests__/test_guia/test_guia_endpoint.py
  sme_terceirizadas/logistica/migrations/0047_insucessoentregaguia_outro_motivo.py
  sme_terceirizadas/logistica/models/guia.py
  sme_terceirizadas/perfil/admin.py
  sme_terceirizadas/perfil/models/usuario.py
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_serializers.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/admin.py
  sme_terceirizadas/produto/api/filters.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0065_produto_editais.py
  sme_terceirizadas/produto/migrations/0066_auto_20220729_0110.py
  sme_terceirizadas/produto/migrations/0067_produtoedital_ativo.py
  sme_terceirizadas/produto/migrations/0068_auto_20220729_0455.py
  sme_terceirizadas/produto/migrations/0069_auto_20220801_0708.py
  sme_terceirizadas/produto/migrations/0070_auto_20220803_0134.py
  sme_terceirizadas/produto/migrations/0071_auto_20220804_1133.py
  sme_terceirizadas/produto/migrations/0072_auto_20220804_1207.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/produto/urls.py
  sme_terceirizadas/produto/utils.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/relatorio_situacao_produto.scss
  sme_terceirizadas/relatorios/templates/relatorio_produtos_situacao.html
  sme_terceirizadas/relatorios/templates/relatorio_reclamacao.html
  sme_terceirizadas/terceirizada/__tests__/conftest.py
  sme_terceirizadas/terceirizada/__tests__/test_url.py
  sme_terceirizadas/terceirizada/api/serializers/serializers.py
  sme_terceirizadas/terceirizada/api/serializers/serializers_create.py
  sme_terceirizadas/terceirizada/models.py
Labels: bug, feature

#1444 Feature: atualizar varios vinculos ao mesmo tempo
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/viewsets.py
Labels: feature

#1445 HOM - Atualizado até 11/08
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/viewsets.py
Labels: feature

#1449 Feature/46673-MI-lançamento-medição-inicial-página-inicial-escola
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0058_auto_20220811_1101.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/validators.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0003_anexoocorrenciamedicaoinicial_responsavel_solicitacaomedicaoinicial_tipocontagemalimentacao.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/urls.py
Labels: enhancement, feature

#1455 Hom - Atualizado até 15/08/22 as 10:55
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0058_auto_20220811_1101.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/validators.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0003_anexoocorrenciamedicaoinicial_responsavel_solicitacaomedicaoinicial_tipocontagemalimentacao.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/urls.py
Labels: enhancement, feature

#1463 Fix: indentacao do escopo da rota de atualizar tipos de alimentação
  sme_terceirizadas/cardapio/api/viewsets.py
Labels: bug

#1462 Feature/68881-PeD-validação-de-log-análise-sensorial
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#1466 Hom - Atualizado até 16/08/22 as 09:35
  .github/workflows/check-status.yml
  .github/workflows/deploy-dev-pipecache.yml
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug, enhancement, feature

#1464 Feature/68882 limpeza de codigo
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/admin.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/migrations/0073_auto_20220816_0216.py
  sme_terceirizadas/produto/models.py
Labels: feature

#1465 Feature: comando para vincular produtos ao edital Pregão n°78/SME/2016
  sme_terceirizadas/produto/management/commands/vincula_produtos_editais.py
Labels: feature

#1467 Hom - Atualizado até 16/08/22 as 10:00
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/admin.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/management/commands/vincula_produtos_editais.py
  sme_terceirizadas/produto/migrations/0073_auto_20220816_0216.py
  sme_terceirizadas/produto/models.py
Labels: feature

#1468 Feature/ajustes-review-59
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: bug, feature

#1469 Hom - Atualizado até 17/08/22 as 10:05
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: feature

#1470 Feature/55022 lista de substitutos escola comum
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/migrations/0033_auto_20220817_0827.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio.html
Labels: feature

#1471 Hom - Atualizado até 17/08/22 as 12:15
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/migrations/0033_auto_20220817_0827.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio.html
Labels: feature

#1472 Feature/ajustes-review-59-pt2
  sme_terceirizadas/medicao_inicial/api/serializers.py
Labels: feature

#1473 Hom - Atualizado até 17/08/22 as 14:45
  sme_terceirizadas/medicao_inicial/api/serializers.py
Labels: feature

#1477 Hom - Atualizado até 17/08/22 as 15:30
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
Labels: feature

#1478 Feature/ajustes-review-59-pt4
  sme_terceirizadas/dados_comuns/utils.py
Labels: feature

#1479 Hom - Atualizado até 17/08/22 as 17:50
  sme_terceirizadas/dados_comuns/utils.py
Labels: feature

#1481 Feature/pytest-coverage-68
  setup.cfg
Labels: enhancement

#1482 Hom atualizado 18/08 as 11:35
  setup.cfg
Labels: enhancement

#1483 Fix: ajustar criação de vinculo produto-edital quando codae homologa
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1484 Hom - Atualizado até 18/08/22 as 14:55
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1486 Feature/71524-PeD-permitir-terceirizada-user-modificar-nome-produto-status-correção
  sme_terceirizadas/produto/utils.py
Labels: feature

#1487 Hom - Atualizado até 19/08/22 as 12:25
  sme_terceirizadas/produto/utils.py
Labels: feature

#1495 Feature: lista nomes editais de acordo com o perfil do usuário
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#1498 Feature: melhorias na filtragem de produtos agrupados por marca e por terceirizada
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/forms.py
  sme_terceirizadas/produto/utils.py
Labels: feature

#1499 Hom - Atualizado até 26/08/22
  .github/workflows/check-status.yml
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/forms.py
  sme_terceirizadas/produto/utils.py
Labels: feature

#1500 Feature/71554 diferenciacao edital protocolo
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/serializers_create.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/migrations/0048_protocolopadraodietaespecial_editais.py
  sme_terceirizadas/dieta_especial/models.py
Labels: feature

#1507 Feature/71710 impressao relatorio
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/relatorios/static/css/_variaveis.scss
  sme_terceirizadas/relatorios/static/css/cabecalho.scss
  sme_terceirizadas/relatorios/static/css/produtos_terceirizada.scss
  sme_terceirizadas/relatorios/templates/homologacao_marcas_por_produto.html
  sme_terceirizadas/relatorios/templates/relatorio_produtos_por_terceirizada.html
Labels: feature

#1508 Hom atualizado 31/08 as 10:00
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/relatorios/static/css/_variaveis.scss
  sme_terceirizadas/relatorios/static/css/cabecalho.scss
  sme_terceirizadas/relatorios/static/css/produtos_terceirizada.scss
  sme_terceirizadas/relatorios/templates/homologacao_marcas_por_produto.html
  sme_terceirizadas/relatorios/templates/relatorio_produtos_por_terceirizada.html
Labels: feature

#1509 Fix: exibição quando editais ou marcas esta vazio, titulo do relatorio
  sme_terceirizadas/relatorios/templates/homologacao_marcas_por_produto.html
  sme_terceirizadas/relatorios/templates/relatorio_produtos_por_terceirizada.html
Labels: bug

#1510 Hom atualizado 31/08 as 17:50
  sme_terceirizadas/relatorios/templates/homologacao_marcas_por_produto.html
  sme_terceirizadas/relatorios/templates/relatorio_produtos_por_terceirizada.html
Labels: bug
