Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-06, with the labels that each got.

#1266 Feature/58665-GA-alteração-solic-inv-cardápio-não-encontra-cardápio
  sme_terceirizadas/cardapio/__tests__/test_serializers_create.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/validators.py
  sme_terceirizadas/cardapio/migrations/0030_auto_20220603_2001.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/validators.py
  sme_terceirizadas/escola/services.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/relatorios/relatorios.py
Labels: feature

#1267 Hom - Atualizado até 06/06/22 as 19:15
  sme_terceirizadas/cardapio/__tests__/test_serializers_create.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/validators.py
  sme_terceirizadas/cardapio/migrations/0030_auto_20220603_2001.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/validators.py
  sme_terceirizadas/escola/services.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/relatorios/relatorios.py
Labels: feature

#1268 Feature/62430 ga solicitacao kit lanche unificado
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
Labels: feature

#1271 HOM - Atualizada 07/06 às 11:35
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
Labels: feature

#1279 Fix/GA-ajuste-ao-fazer-requisicao-turno-noite-metodo-calendario_sgp
  sme_terceirizadas/escola/utils.py
Labels: bug

#1280 Hom - Atualizado até 07/06/22 as 16:55
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/fluxo_codae_autoriza_ou_nega_dieta.html
  sme_terceirizadas/dieta_especial/models.py
  sme_terceirizadas/escola/utils.py
Labels: bug, feature

#1287 Feature/65427 xlsx na central de download
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/logistica/api/services/exporta_para_excel.py
  sme_terceirizadas/logistica/api/viewsets.py
  sme_terceirizadas/logistica/management/commands/atualiza_data_entrega_guias.py
  sme_terceirizadas/logistica/migrations/0044_logsolicitacaodecancelamentopelopapa.py
  sme_terceirizadas/logistica/tasks.py
Labels: feature

#1289 Feature/65382-GA-limitar-período-merenda-seca-em-5-dias-úteis
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/dados_comuns/api/viewsets.py
Labels: feature

#1290 Hom - Atualizado até 10/06/22 as 11:35
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/dados_comuns/api/viewsets.py
Labels: feature

#1291 Fix/65383-PeD-problema-reenvio-de-produtos-não-homologados
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: bug

#1292 Hom - Atualizado até 10/06/22 as 16:10
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: bug

#1304 Fix: add quantidade_alunos no payload
  sme_terceirizadas/escola/api/serializers.py
Labels: bug

#1307 Feature/66489-DE-melhoria-visualização-relatório-de-protocolo
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial_protocolo.html
Labels: feature

#1308 Hom - Atualizado até 16/06/22 as 14:50
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial_protocolo.html
Labels: feature

#1310 Hom - Atualizado até 20/06/22 as 14:15
  sme_terceirizadas/dieta_especial/api/serializers.py
Labels: bug

#1318 Feature/59030-DE-incluir-foto-na-tela-dieta-especial-autorizada
  sme_terceirizadas/escola/api/permissions.py
Labels: feature

#1319 Hom - Atualizado até 27/06/22 as 18:10
  sme_terceirizadas/escola/api/permissions.py
Labels: feature

#1324 Fix/67466-DE-filtro-de-dietas-autorizadas-remover-dietas-inativas-tela-relatorio
  sme_terceirizadas/dieta_especial/api/viewsets.py
Labels: bug

#1322 Feature/59034-DE-incluir-foto-na-tela-consulta-dieta-especial
  sme_terceirizadas/dieta_especial/api/serializers.py
Labels: feature

#1331 Fix/67847-GA-erro-contagem-card-pendências-dre-e-codae
  sme_terceirizadas/paineis_consolidados/migrations/0019_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0018_solicitacoes.sql
Labels: bug

#1332 Hom - Atualizado até 30/06/22 as 09:10
  sme_terceirizadas/paineis_consolidados/migrations/0019_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/sql/0018_solicitacoes.sql
Labels: bug

#1334 Feature/66588-DE-incluir-classificação-dieta-ativa-tela-consulta-de-dieta-do-aluno
  sme_terceirizadas/dieta_especial/api/serializers.py
Labels: feature
