Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2022-02, with the labels that each got.

#1043 Feature: validação nome em caixa alta e duplicidade
  sme_terceirizadas/dieta_especial/api/serializers_create.py
Labels: feature

#1044 Hom - Atualizado até 01/02/22 as 03:30
  sme_terceirizadas/dieta_especial/api/serializers_create.py
Labels: feature

#1045 Feature/53994-PD-criar-cards-de-responder-questionamentos-da-codae
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#1046 Hom - Atualizado até 01/02/22 as 08:00
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#1047 Fix: correção na montagem da url nos ambientes de homologação, treinamento, produção para o serializer de produto
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: bug

#1048 Hom - Atualizado até 01/02/22 as 12:50
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: bug

#1049 Fix: deletar matriculas por escola/turno ao rodar tarefa
  sme_terceirizadas/escola/utils.py
Labels: bug

#1050 Hom - Atualizado até 01/02/22 as 13:20
  sme_terceirizadas/escola/utils.py
Labels: bug

#1051 Fix: mensagem de erro ao tentar cadastrar um nome de protocolo existente
  sme_terceirizadas/dieta_especial/api/serializers_create.py
Labels: bug

#1052 Hom - Atualizado até 02/02/22 as 13:30
  sme_terceirizadas/dieta_especial/api/serializers_create.py
Labels: bug

#1053 Prod - Atualizado até 03/02/2022 as 03:45
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dieta_especial/api/serializers_create.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/logistica/api/viewsets.py
  sme_terceirizadas/logistica/services.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/utils.py
Labels: bug, feature

#1056 Feature/54737 criar usuario nutricionista manifestacao
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/perfil/models/usuario.py
  utility/carga_dados/perfil/importa_dados.py
  utility/carga_dados/usuarios.py
Labels: feature

#1059 Feature/54737 criar usuario nutricionista manifestacao
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/perfil/models/usuario.py
  utility/carga_dados/perfil/importa_dados.py
  utility/carga_dados/usuarios.py
Labels: feature

#1060 Feature/56234-PD-alteração-na-tela-de-cadastro-do-produto-retirar-campo-de-protocolo
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/utils.py
Labels: feature

#1061 Hom - Atualizado até 03/02/22 as 18:00
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/utils.py
Labels: feature

#1062 Feature/56232-PD-homologação-e-correção-de-produto-checar-campos-nome-e-alunos-com-dieta
  sme_terceirizadas/produto/utils.py
Labels: feature

#1063 Hom - Atualizado até 04/02/22 as 19:30
  sme_terceirizadas/produto/utils.py
Labels: feature

#1065 Feature: endpoint deve devolver paginado ou não de acordo com a requisição
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#1068 Hom - Atualizado até 09/02/22 as 18:25
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#1069 Hotfix/correcao task cancelamento
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/eol_servico/utils.py
Labels: bug

#1070 Bugfix/correcao task cancelamento
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/eol_servico/utils.py
Labels: bug

#1071 Hom - Atualizado até 10/02/22 as 16:40
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/eol_servico/utils.py
Labels: bug

#1072 Feature/57884-DE-criar-permissionamento-nutricionista-manifestação
  sme_terceirizadas/dados_comuns/permissions.py
Labels: feature

#1073 Hom - Atualizado até 15/02/22 as 19:40
  sme_terceirizadas/dados_comuns/permissions.py
Labels: feature

#1074 Feature/validacoes ao atualizar matriculas ativas
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/eol_servico/utils.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
Labels: feature

#1075 Hom - Atualizado até 19/02/22 as 18:45
  .github/workflows/deploy-dev-sem-testes.yml
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy.yml
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/eol_servico/utils.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
Labels: feature

#1076 Feature/refatoracao task cancela dietas ativas
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/eol_servico/utils.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
Labels: feature

#1081 Hom - Atualizado até 21/02/22 as 18:15
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#1082 Prod - Atualizado até 21/02/2022 as 19:40
  config/settings/base.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/eol_servico/utils.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/logistica/api/soup/views.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#1083 Feature/57885-GA-criar-permissionamento-nutricionista-manifestação
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/urls.py
Labels: feature

#1084 Hom - Atualizado até 22/02/22 as 13:25
  .github/workflows/deploy-dev-pipecache.yml
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/urls.py
Labels: feature

#1085 feature/59171 ajuste no webservice
  sme_terceirizadas/logistica/api/soup/models.py
  sme_terceirizadas/logistica/api/soup/views.py
Labels: feature

#1087 Prod - Atualizado até 22/02/2022 as 17:40
  .github/workflows/deploy-dev-pipecache.yml
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/logistica/api/soup/models.py
  sme_terceirizadas/logistica/api/soup/views.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/urls.py
Labels: feature

#1088 Feature/57633-DE-alterar-texto-de-email-ao-autorizar-dieta
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/email_base.html
  sme_terceirizadas/dados_comuns/templates/fluxo_codae_autoriza_dieta.html
Labels: feature

#1089 Hom - Atualizado até 23/02/22 as 18:10
  .github/workflows/deploy-dev-pipecache.yml
  .github/workflows/deploy-dev.yml
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/email_base.html
  sme_terceirizadas/dados_comuns/templates/fluxo_codae_autoriza_dieta.html
Labels: feature

#1090 Feature: usar codigo codae para atribuir escola em dieta especial
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
Labels: feature

#1091 Fix: validacao de matricula transferida e cancelada
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
Labels: bug

#1092 Hom - Atualizado até 24/02/22 as 11:45
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
Labels: bug, feature

#1095 Bugfix/59164 endereco email terceirizada e escola
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
Labels: bug

#1096 Hom - Atualizado até 25/02/22 as 03:30
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
Labels: bug

#1097 Fix: enviar email apenas em prod
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: bug

#1098 Hom - Atualizado até 25/02/22 as 11:40
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: bug
