Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-09, with the labels that each got.

#2873 Fix/ajustar-função-append_faixas_dietas
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/__tests__/conftest.py
Labels: bug, enhancement

#2874 Prod atualizado 01/09 as 18h45
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/__tests__/conftest.py
Labels: bug, enhancement

#2875 Hom atualizado 01/09 as 18h50
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/__tests__/conftest.py
Labels: bug, enhancement

#2876 Dev atualizado 01/09 as 19h00
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/__tests__/conftest.py
Labels: bug, enhancement

#2887 Feature/102084-MI-criar-task-para-excluir-logs-duplicados-e-criar-logs-inexistentes
  sme_terceirizadas/dados_comuns/__tests__/conftest.py
  sme_terceirizadas/dados_comuns/__tests__/test_utils.py
  sme_terceirizadas/dados_comuns/management/commands/__init__.py
  sme_terceirizadas/dados_comuns/management/commands/deletar_e_criar_logs_dietas_e_matriculados.py
  sme_terceirizadas/dados_comuns/tasks.py
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/dieta_especial/__tests__/test_utils.py
  sme_terceirizadas/dieta_especial/tasks.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/migrations/0061_alter_logalunosmatriculadosperiodoescola_options.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/utils.py
Labels: enhancement, feature, refactoring

#2888 Hom atualizado 06/09 as 11h25
  sme_terceirizadas/dados_comuns/__tests__/conftest.py
  sme_terceirizadas/dados_comuns/__tests__/test_utils.py
  sme_terceirizadas/dados_comuns/management/commands/__init__.py
  sme_terceirizadas/dados_comuns/management/commands/deletar_e_criar_logs_dietas_e_matriculados.py
  sme_terceirizadas/dados_comuns/tasks.py
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/dieta_especial/__tests__/test_utils.py
  sme_terceirizadas/dieta_especial/tasks.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/migrations/0061_alter_logalunosmatriculadosperiodoescola_options.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/utils.py
Labels: enhancement, feature, refactoring

#2899 Hom - Atualizado em 13/09 as 10h20
  sme_terceirizadas/escola/admin.py
Labels: enhancement

#2898 Feature: adaptação do endpoint para devolver inclusões CEI formatadas
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: feature

#2909 HOM - Atualizado em 13/09 às 15:20h
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/pre_recebimento_notificacao_alteracao_cronograma_codae.html
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: feature

#2918 Fix: faixas etárias devem pertencer aos períodos corretos
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: bug

#2919 HOM - Atualizado em 14/09 às 15:50
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: bug

#2931 Feature/103188 medicao inclusoes evento especifico
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: feature

#2932 HOM - atualizado até 19/09
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: feature

#2927 Feature/102647-MI-integração-gestão-alimentação-escolas-cei-manhã-e-tarde-não-letivo
  sme_terceirizadas/paineis_consolidados/__tests__/conftest.py
  sme_terceirizadas/paineis_consolidados/__tests__/test_url.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: enhancement, feature

#2933 Hom - Atualizado em 19/09 as 17h35
  sme_terceirizadas/paineis_consolidados/__tests__/conftest.py
  sme_terceirizadas/paineis_consolidados/__tests__/test_url.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: enhancement, feature

#2934 Feature/99995-MI-integração-gestão-alimentação-suspensão-alimentação-escolas-cei
  sme_terceirizadas/paineis_consolidados/__tests__/conftest.py
  sme_terceirizadas/paineis_consolidados/__tests__/test_url.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/utils.py
Labels: enhancement, feature

#2971 Feature: validar campos da medição ao enviar para DRE
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/validators.py
Labels: feature

#2972 Hom - Aualizado 28/09 às 15:00h
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/validators.py
Labels: feature

#2977 Fix: limitar validação apenas para escolas descritas na atividade
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
Labels: feature

#2979 Fix: metodo para validação de dietas especiais deve respeitar regras de alimentacoes abertas para preenchimento
  sme_terceirizadas/medicao_inicial/validators.py
Labels: bug

#2980 HOM - Atualizado em 29/09 às 2023
  sme_terceirizadas/medicao_inicial/validators.py
Labels: bug
