Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-07, with the labels that each got.

#2625 Fix: validação de diferença entre os querysets
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#2626 HOM - Atualizado em 03/06 às 13:20h
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#2627 Feature/98356-TEC-trocar-biblioteca-do-swagger
  config/urls.py
  sme_terceirizadas/templates/base.html
Labels: enhancement

#2628 Feature/98356-TEC-trocar-biblioteca-do-swagger
  config/urls.py
  sme_terceirizadas/templates/base.html
Labels: enhancement

#2631 Hom Atualizado 03/07 as 19h30
  config/settings/base.py
  config/settings/local.py
  sme_terceirizadas/templates/base.html
Labels: enhancement

#2633 Feature/96924-PeD-inserir-nome-dre-tela-reclamação-de-produto
  sme_terceirizadas/escola/__tests__/test_serializers.py
  sme_terceirizadas/escola/api/serializers.py
Labels: enhancement, feature

#2634 Hom Atualizado 04/07 as 14h05
  sme_terceirizadas/escola/__tests__/test_serializers.py
  sme_terceirizadas/escola/api/serializers.py
Labels: enhancement, feature

#2643 Feature/96903-GA-alteração-alimentação-RPL-e-LPR-somente-em-dias-úteis
  sme_terceirizadas/dados_comuns/api/viewsets.py
  sme_terceirizadas/dados_comuns/urls.py
Labels: enhancement, feature

#2644 Hom Atualizado 06/07 as 16h25
  sme_terceirizadas/dados_comuns/api/viewsets.py
  sme_terceirizadas/dados_comuns/urls.py
Labels: enhancement, feature

#2665 Feature/97573 justificativa codae ao autorizar
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/relatorios/templates/bloco_observacao_codae_autoriza.html
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio.html
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio_cei.html
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio_cemei.html
Labels: feature

#2666 HOM - Atualizado até 12/07 às 14:10h
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/relatorios/templates/bloco_observacao_codae_autoriza.html
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio.html
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio_cei.html
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio_cemei.html
Labels: feature

#2668 Fix: resultado deve conter produtos com vinculos de editais suspensos
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#2669 HOM - Atualizado em 12/07 às 16:20h
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#2671 Feature/97570-GA-modal-observação-na-autorização-inclusão-alimentação-codae
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/relatorios/templates/bloco_historico_questionamento_com_data.html
  sme_terceirizadas/relatorios/templates/bloco_observacao_codae_autoriza.html
  sme_terceirizadas/relatorios/templates/novo_solicitacao_inclusao_alimentacao_cei.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_continua.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_normal.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#2673 Hom Atualizado 14/07 as 10h20
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/tasks.py
  sme_terceirizadas/relatorios/templates/bloco_historico_questionamento_com_data.html
  sme_terceirizadas/relatorios/templates/bloco_observacao_codae_autoriza.html
  sme_terceirizadas/relatorios/templates/novo_solicitacao_inclusao_alimentacao_cei.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_continua.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_normal.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#2674 Feature/97425 observacao ao autorizar kit lanche
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_cemei.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_passeio.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_passeio_cei.html
Labels: feature

#2675 Hom - Atualizado até 14/07 às 16:20h
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_cemei.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_passeio.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_passeio_cei.html
Labels: feature

#2679 Feature/pt_2-testes-unitários-sprint-81
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
Labels: enhancement

#2693 Hom Atualizado 19/07 as 10h50
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2696 Feature/93436-MI-aprovação-medição-inicial-pela-codae
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2697 Hom Atualizado 20/07 as 11h55
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2698 Feature/93458-MI-envio-email-para-ue-sobre-aprovação-medição-pela-codae
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/medicao_dre_codae_aprova_solicitacao.html
Labels: enhancement, feature

#2699 Hom Atualizado 20/07 as 15h25
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/medicao_dre_codae_aprova_solicitacao.html
Labels: enhancement, feature

#2703 Feature/93459-MI-envio-solicitação-de-correção-pela-codae
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0093_alter_logsolicitacoesusuario_status_evento.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2704 Hom Atualizado 21/07 as 16h55
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0093_alter_logsolicitacoesusuario_status_evento.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2708 Feature: funcionalidade para permitir solicitar correção da medição com perfil CODAE
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: feature

#2711 HOM - Atualizado em 24/07 às 15:40
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: feature

#2719 HOM - Atualizado em 25/07 às 17:00
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: feature

#2721 Feature/99125-MI-envio-correção-para-codae-visão-ue
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0094_alter_logsolicitacoesusuario_status_evento.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2722 HOM - Atualizado 25/07 às 18:15
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0094_alter_logsolicitacoesusuario_status_evento.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/pre_recebimento/__tests__/conftest.py
  sme_terceirizadas/pre_recebimento/__tests__/test_models.py
  sme_terceirizadas/pre_recebimento/__tests__/test_serializers.py
  sme_terceirizadas/pre_recebimento/__tests__/test_urls.py
  sme_terceirizadas/pre_recebimento/admin.py
  sme_terceirizadas/pre_recebimento/api/filters.py
  sme_terceirizadas/pre_recebimento/api/serializers/serializer_create.py
  sme_terceirizadas/pre_recebimento/api/serializers/serializers.py
  sme_terceirizadas/pre_recebimento/api/viewsets.py
  sme_terceirizadas/pre_recebimento/migrations/0011_unidademedida.py
  sme_terceirizadas/pre_recebimento/migrations/0012_alter_unidademedida_options.py
  sme_terceirizadas/pre_recebimento/models/__init__.py
  sme_terceirizadas/pre_recebimento/models/cronograma.py
  sme_terceirizadas/pre_recebimento/urls.py
  sme_terceirizadas/pre_recebimento/utils.py
  sme_terceirizadas/produto/__tests__/conftest.py
Labels: enhancement, feature

#2733 Feature/99127-MI-ocorrências-e-períodos-devolvidos-para-ajustes-pela-codae-visão-ue
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: enhancement, feature

#2734 Hom Atualizado 28/07 as 19h00
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/eol_servico/api/viewsets.py
  sme_terceirizadas/eol_servico/urls.py
  sme_terceirizadas/escola/__tests__/test_urls.py
  sme_terceirizadas/escola/api/serializers_create.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/urls.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
  sme_terceirizadas/terceirizada/__tests__/conftest.py
  sme_terceirizadas/terceirizada/__tests__/test_url.py
  sme_terceirizadas/terceirizada/api/viewsets.py
  sme_terceirizadas/terceirizada/models.py
  sme_terceirizadas/terceirizada/urls.py
Labels: enhancement, feature

#2737 Feature: permitir CODAE aprovar periodo
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: feature

#2738 HOM - Atualizado em 31/07/2023 às 14:00h
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: feature

#2739 Feature/testes-unitarios-urls-viewsets-medicao
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
Labels: enhancement

#2740 Hom Atualizado 31/07 as 20h30
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
Labels: enhancement
