Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-03, with the labels that each got.

#2170 Feature/86398-GA-relatorio-sol-alimentacao-ajustar-periodos-escola-cei-infantil
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
Labels: enhancement, feature

#2171 Hom Atualizado 01/03 às 13:40
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/produto_codae_aceitou_reclamacao.html
  sme_terceirizadas/dados_comuns/templates/produto_codae_suspende.html
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
Labels: enhancement, feature

#2174 Feature/86230-GA-inserir-ID-solicitação-no-resultado-relatório-de-solicitações-alimentação
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/paineis_consolidados/tasks.py
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
  sme_terceirizadas/relatorios/templates/bloco_inversao_dia_cardapio.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cei.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_unificado.html
  sme_terceirizadas/relatorios/templates/bloco_suspensao_alimentacao.html
  sme_terceirizadas/relatorios/templates/bloco_suspensao_alimentacao_cei.html
Labels: enhancement, feature

#2175 Hom Atualizado 02/03 as 16h05
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/paineis_consolidados/tasks.py
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_alteracao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
  sme_terceirizadas/relatorios/templates/bloco_inversao_dia_cardapio.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cei.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_unificado.html
  sme_terceirizadas/relatorios/templates/bloco_suspensao_alimentacao.html
  sme_terceirizadas/relatorios/templates/bloco_suspensao_alimentacao_cei.html
Labels: enhancement, feature

#2178 Feature/87382-PeD-incluir-no-histórico-do-produto-datas-de-vínculos-dos-editais
  sme_terceirizadas/dados_comuns/migrations/0079_alter_logsolicitacoesusuario_status_evento.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
Labels: enhancement, feature

#2186 Feature/85801 filtros relatorio alunos matriculados
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/urls.py
Labels: feature

#2187 HOM - Atualizada até 07/03 às 15:40
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/urls.py
Labels: feature

#2199 Feature/85622-MI-visualização-de-medição-DRE
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2202 Hom Atualizado 08/03 as 14h40
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2201 Feature/86230-GA-ajustar-exibição-de-ID-solicitação
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
  sme_terceirizadas/relatorios/templates/bloco_suspensao_alimentacao.html
Labels: enhancement

#2203 Hom Atualizado 08/03 as 14h55
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
  sme_terceirizadas/relatorios/templates/bloco_suspensao_alimentacao.html
Labels: enhancement

#2209 Feature/85625-MI-visualização-lançamentos-de-período-DRE
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0013_auto_20230310_1710.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#2210 Hom Atualizado 13/03 as 10h30
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0013_auto_20230310_1710.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#2213 Feature: Resultado para endpoint de alunos matriculados
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
Labels: feature

#2214 Hom Atualizado 13/03 as 13h30
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
Labels: feature

#2218 Hom Atualizado 14/03 as 15h20
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: feature

#2219 Feature/85636-MI-solicitação-correção-período-de-lançamento-dre
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0014_valormedicao_habilitado_correcao.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#2220 Hom Atualizado 15/03 as 09h00
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0014_valormedicao_habilitado_correcao.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#2221 Bugfix/85801 opcoes corretas dos filtros
  sme_terceirizadas/escola/api/viewsets.py
Labels: bug

#2222 Hom Atualizado 15/03 as 16h10
  sme_terceirizadas/escola/api/viewsets.py
Labels: bug

#2230 Feature: command para exportação da planilha de verificação dos protocolos
  sme_terceirizadas/dieta_especial/management/commands/exportar_planilha_relacao_protocolo.py
Labels: feature

#2232 Hom atualizado 21/03 as 09h41
  sme_terceirizadas/dieta_especial/management/commands/exportar_planilha_relacao_protocolo.py
Labels: feature

#2236 Feature/70951-MI-tela-ue-lançamento-de-solicitações-de-alimentação
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/fixtures/categorias_de_medicao.yaml
  sme_terceirizadas/medicao_inicial/migrations/0015_altera_nome_grupo.py
  sme_terceirizadas/medicao_inicial/migrations/0016_alter_medicao_periodo_escolar.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/paineis_consolidados/api/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: enhancement, feature

#2239 Hom Atualizado 23/03 as 18h35
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/fixtures/categorias_de_medicao.yaml
  sme_terceirizadas/medicao_inicial/migrations/0015_altera_nome_grupo.py
  sme_terceirizadas/medicao_inicial/migrations/0016_alter_medicao_periodo_escolar.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/paineis_consolidados/api/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: enhancement, feature

#2241 Hom Atualizado 23/03 as 18h55
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/fluxo_codae_autoriza_dieta.html
  sme_terceirizadas/dados_comuns/templates/fluxo_codae_nega_dieta.html
Labels: enhancement, feature

#2238 Fix: deve filtrar AlunosMatriculadosPeridoEscolar ao invés de Escola
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
Labels: bug

#2243 Hom-r2 atualizado 24/03 as 09h10
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
Labels: bug

#2245 DEV atualizado 24/03 as 09h10
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
Labels: bug

#2242 Feature/88661 primeiro acesso usuarios servidores
  sme_terceirizadas/dados_comuns/templates/email_primeiro_acesso_usuario_servidor.html
  sme_terceirizadas/perfil/api/serializers.py
  sme_terceirizadas/perfil/models/usuario.py
Labels: feature

#2246 Feature: relacionar protocolos quando encontrar, devolver log de erro quando estiver errado
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
Labels: feature

#2247 Hom atualizado 24/03 as 10h10
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
Labels: feature

#2249 Feature/85802-GA-relatório-alunos-matriculados-dre
  sme_terceirizadas/escola/api/viewsets.py
Labels: enhancement

#2250 Hom Atualizado 24/03 as 17h30
  sme_terceirizadas/escola/api/viewsets.py
Labels: enhancement

#2251 Feature/85803-GA-relatorio-alunos-matriculados-para-nutrimanifestação-nutrisupervisão-codae-medicão
  sme_terceirizadas/escola/api/viewsets.py
Labels: enhancement

#2253 Hom Atualizado 27/03 as 11h30
  sme_terceirizadas/escola/api/viewsets.py
Labels: enhancement

#2255 Hom Atualizado 27/03 as 12h30
  sme_terceirizadas/escola/api/viewsets.py
Labels: enhancement

#2263 Feature/90313-GA-possibilitar-acesso-unidades-p-fom-para-realizar-solicitações-gestão-alimentação
  sme_terceirizadas/cardapio/tasks.py
  sme_terceirizadas/escola/utils.py
Labels: enhancement, feature

#2264 Hom Atualizado 28/03 as 18h50
  sme_terceirizadas/cardapio/tasks.py
  sme_terceirizadas/escola/utils.py
Labels: enhancement, feature

#2258 Feature/88746 criar endpoints para solocitacoes terceirizadas
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
Labels: feature

#2266 Hom Atualizado 29/03 as 02h10
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
Labels: feature

#2265 Fix: remover metodos para calcular similaridade dos nomes de protocolos
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
Labels: bug

#2269 Feature/85802-GA-relatório-alunos-matriculados-dre
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/utils.py
Labels: enhancement

#2273 Fix/90458-GA-ajustar-filtros-dinâmicos-de-lote-ue-tela-relatório-alunos-matriculados
  sme_terceirizadas/escola/api/serializers.py
Labels: bug

#2274 Hom Atualizado 29/03 as 19h10
  sme_terceirizadas/escola/api/serializers.py
Labels: bug

#2277 Feature/88622 relacionar protocolos a dietas
  sme_terceirizadas/dieta_especial/management/commands/fix_nomes_protocolos.py
  sme_terceirizadas/dieta_especial/management/commands/processar_planilha_protocolos_invalidos.py
  sme_terceirizadas/dieta_especial/management/commands/processar_planilha_protocolos_validos.py
Labels: feature

#2279 Hom Atualizado 30/03 as 11:20
  sme_terceirizadas/dieta_especial/management/commands/fix_nomes_protocolos.py
  sme_terceirizadas/dieta_especial/management/commands/processar_planilha_protocolos_invalidos.py
  sme_terceirizadas/dieta_especial/management/commands/processar_planilha_protocolos_validos.py
Labels: feature

#2281 Bugfix/89124 filtros tela cronograma
  sme_terceirizadas/pre_recebimento/api/filters.py
Labels: bug
