Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-02, with the labels that each got.

#2064 Fix: tabela de faixas etárias CEI deve exibir apenas faixas com frequência de alunos
  sme_terceirizadas/relatorios/templates/novo_solicitacao_inclusao_alimentacao_cei.html
Labels: bug

#2071 Feature/73029-PeD-gestão-de-editais-suspender-produto-por-edital
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0069_auto_20230203_1228.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0075_auto_20230201_2037.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/produto/utils.py
  sme_terceirizadas/relatorios/templates/ficha_identificacao_produto.html
Labels: enhancement, feature

#2072 Hom Atualizado 03/02 as 17h10
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0069_auto_20230203_1228.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0075_auto_20230201_2037.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/produto/utils.py
  sme_terceirizadas/relatorios/templates/ficha_identificacao_produto.html
Labels: enhancement, feature

#2078 Feature/84543-PeD-hover-tooltip-dashboard-cards-homologados-suspensos
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: enhancement, feature

#2084 Hom Atualizado 07/02 as 12h10
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0069_auto_20230205_1805.py
  sme_terceirizadas/dados_comuns/migrations/0070_merge_0069_auto_20230203_1228_0069_auto_20230205_1805.py
  sme_terceirizadas/dados_comuns/migrations/0071_alter_logsolicitacoesusuario_status_evento.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/perfil/models/usuario.py
  sme_terceirizadas/pre_recebimento/__tests__/test_urls.py
  sme_terceirizadas/pre_recebimento/api/viewsets.py
  sme_terceirizadas/produto/api/serializers/serializers.py
Labels: enhancement, feature

#2092 Feature: adicionar períodos padrões para unidades CCI e CEICEU
  sme_terceirizadas/escola/models.py
Labels: feature

#2098 Hom - Atualizado até 09/02 as 16:30
  sme_terceirizadas/escola/models.py
Labels: feature

#2100 Feature/76445-MI-salvamento-automático-dos-lançamentos
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0008_medicao_alterado_em.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#2101 Hom Atualizado 10/02 as 12h15
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0008_medicao_alterado_em.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#2110 Feature/84946 atualiza taks para vinculos cei
  sme_terceirizadas/cardapio/tasks.py
  sme_terceirizadas/escola/models.py
Labels: feature

#2112 Hom atualizado 13/02 as 16h20
  sme_terceirizadas/cardapio/tasks.py
  sme_terceirizadas/escola/models.py
Labels: feature

#2114 Feature/84633 filtros dashboard medicao inicial
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: feature

#2121 Fix: matriculados por faixa no relatório CEI
  sme_terceirizadas/relatorios/relatorios.py
Labels: bug

#2122 Hom atualizado 15/02 as 18:45
  sme_terceirizadas/relatorios/relatorios.py
Labels: bug

#2138 Feature/85719-PeD-tela-ativar-suspender--filtros-produtos-parcialmente-suspenso
  sme_terceirizadas/produto/api/filters.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: enhancement, feature

#2147 Hom Atualizado 22/02 às 17:50
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/pre_recebimento/__tests__/conftest.py
  sme_terceirizadas/pre_recebimento/__tests__/test_urls.py
  sme_terceirizadas/pre_recebimento/api/viewsets.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/filters.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/models.py
  sme_terceirizadas/produto/tasks.py
  sme_terceirizadas/produto/utils.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/homologacao_marcas_por_produto.html
Labels: feature

#2149 Feature/84949 criar periodo externo inclusao cei
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0033_quantidadedealunosporfaixaetariadainclusaodealimentacaodacei_periodo_externo.py
  sme_terceirizadas/inclusao_alimentacao/models.py
Labels: feature

#2151 Hom Atualizado 24/02 às 12:00
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers_create.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0033_quantidadedealunosporfaixaetariadainclusaodealimentacaodacei_periodo_externo.py
  sme_terceirizadas/inclusao_alimentacao/models.py
Labels: feature

#2152 Feature/72115-MI-integração-com-gestão-alimentação--suspensão-e-alteração
  sme_terceirizadas/paineis_consolidados/api/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: enhancement, feature

#2153 Hom Atualizado 24/02 às 14:20
  sme_terceirizadas/paineis_consolidados/api/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: enhancement, feature

#2159 Feature/85719-PeD-tela-ativar-suspender-produto-resultado-filtro-e-relatório
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: enhancement, feature

#2161 Hom Atualizado 28/02 às 10:55
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: enhancement, feature

#2160 Feature/86386 aplicar alteracoes relatorio cei pdf
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/novo_solicitacao_inclusao_alimentacao_cei.html
Labels: feature
