Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-06, with the labels that each got.

#2530 Feature/93527 correcao de ocorrencia pela ue
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_models.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0019_auto_20230531_0607.py
  sme_terceirizadas/medicao_inicial/migrations/0020_auto_20230531_0609.py
  sme_terceirizadas/medicao_inicial/migrations/0021_delete_anexoocorrenciamedicaoinicial.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: feature

#2544 Feature/93529-MI-detalhamento-períodos-devolvidos-para-ajustes-pela-dre-visão-UE
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2545 Hom Atualizado 06/06 as 11h55
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2546 Feature/93529-MI-detalhamento-períodos-devolvidos-para-ajustes-pela-dre-visão-UE
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#2547 Hom Atualizado 06/06 as 15h30
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#2550 Fix: exibir datas lado a lado e corrigir nomeclatura
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio.html
Labels: bug

#2557 Feature/94417-MI-programas-e-projetos-unificar-períodos-nos-lançamentos
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: enhancement, feature

#2566 Feature/94417-MI-programas-e-projetos-unificar-períodos-nos-lançamentos
  sme_terceirizadas/escola/api/viewsets.py
Labels: enhancement

#2567 Hom Atualizado 13/06 as 19h00
  sme_terceirizadas/escola/api/viewsets.py
Labels: enhancement

#2568 Feature/95393-MI-alterações-relatório-pdf-medição-inicial-após-unificar-programas-e-projetos
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement

#2569 Hom Atualizado 14/06 as 16h40
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement

#2575 Feature: cobertura de testes para ocorrências da medição inicial
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
Labels: feature

#2579 Hom - atualizado em 15/06 às 16:15h
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
Labels: feature

#2580 PROD - Atualizado em 16/06 às 10:30
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0090_alter_logsolicitacoesusuario_solicitacao_tipo.py
  sme_terceirizadas/dados_comuns/migrations/0090_alter_logsolicitacoesusuario_status_evento.py
  sme_terceirizadas/dados_comuns/migrations/0091_merge_20230608_1101.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/logistica/admin.py
  sme_terceirizadas/logistica/api/filters.py
  sme_terceirizadas/logistica/api/serializers/serializer_create.py
  sme_terceirizadas/logistica/api/serializers/serializers.py
  sme_terceirizadas/logistica/api/viewsets.py
  sme_terceirizadas/logistica/migrations/0049_auto_20230606_1549.py
  sme_terceirizadas/logistica/migrations/0050_previsaocontratualnotificacao.py
  sme_terceirizadas/logistica/migrations/0051_auto_20230608_1204.py
  sme_terceirizadas/logistica/models/__init__.py
  sme_terceirizadas/logistica/models/guia.py
  sme_terceirizadas/logistica/urls.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
  sme_terceirizadas/relatorios/templates/solicitacao_alteracao_cardapio.html
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
  sme_terceirizadas/relatorios/templatetags/index.py
  sme_terceirizadas/terceirizada/utils.py
Labels: feature

#2588 Feature/96847-GA-relatório-solicitações-alimentação-dias-com-cancelamento-inclusão-cei-cemei
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/paineis_consolidados/tasks.py
  sme_terceirizadas/paineis_consolidados/utils.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacoes_alimentacao.scss
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
Labels: enhancement, feature

#2591 Feature/96840-GA-relatório-solicitações-alimentação-dias-com-cancelamento-inclusão-normal-contínua
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/paineis_consolidados/tasks.py
  sme_terceirizadas/paineis_consolidados/utils.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacoes_alimentacao.scss
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
Labels: enhancement, feature

#2592 Hom Atualizado 21/06 as 16h55
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/paineis_consolidados/tasks.py
  sme_terceirizadas/paineis_consolidados/utils.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacoes_alimentacao.scss
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_continua.html
  sme_terceirizadas/relatorios/templates/bloco_inclusao_normal.html
Labels: enhancement, feature

#2601 Feature/96447 incluir editais no historico
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_utils.py
  sme_terceirizadas/dieta_especial/api/serializers_create.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: feature

#2594 Feature/96112 vincular protocolos editais
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_utils.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/serializers_create.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/migrations/0054_protocolopadraodietaespecial_outras_informacoes.py
  sme_terceirizadas/dieta_especial/models.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: feature

#2619 Feature/96066-GA-inclusão-de-alimentação-motivo-específico
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0034_adicionamotivosinclusaoalimentacao.py
Labels: enhancement, feature

#2620 Hom Atualizado 30/06 as 11h30
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0034_adicionamotivosinclusaoalimentacao.py
Labels: enhancement, feature

#2622 Feature/98356-TEC-trocar-biblioteca-do-swagger
  Pipfile
  Pipfile.lock
  config/settings/base.py
  config/urls.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
Labels: enhancement, feature

#2624 Feature/98356-TEC-trocar-biblioteca-do-swagger
  config/urls.py
Labels: enhancement

#2623 Hom Atualizado 30/06 as 17h30
  Pipfile
  Pipfile.lock
  config/settings/base.py
  config/urls.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
Labels: enhancement, feature
