Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-10, with the labels that each got.

#2998 Feature/103449-MI-visualização-tela-lançamento-período-DRE-escolas-cei
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2999 Hom - Atualizado em 04/10 as 12h55
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0101_alter_logsolicitacoesusuario_status_evento.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/pre_recebimento/__tests__/conftest.py
  sme_terceirizadas/pre_recebimento/__tests__/test_urls.py
  sme_terceirizadas/pre_recebimento/api/filters.py
  sme_terceirizadas/pre_recebimento/api/serializers/serializer_create.py
  sme_terceirizadas/pre_recebimento/api/serializers/serializers.py
  sme_terceirizadas/pre_recebimento/api/viewsets.py
  sme_terceirizadas/pre_recebimento/migrations/0022_alter_layoutdeembalagem_status.py
  sme_terceirizadas/pre_recebimento/migrations/0023_alter_tipodeembalagemdelayout_unique_together.py
  sme_terceirizadas/pre_recebimento/models/cronograma.py
  sme_terceirizadas/pre_recebimento/utils.py
Labels: enhancement, feature

#3005 Feature: adicionar historico de correções para CODAE
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: feature

#3014 Hom - Atualizado em 05/23 às 15:40
  sme_terceirizadas/conftest.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/migrations/0102_alter_logsolicitacoesusuario_status_evento.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/validators.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/pre_recebimento/__tests__/conftest.py
  sme_terceirizadas/pre_recebimento/__tests__/test_urls.py
  sme_terceirizadas/pre_recebimento/admin.py
  sme_terceirizadas/pre_recebimento/api/serializers/serializer_create.py
  sme_terceirizadas/pre_recebimento/api/viewsets.py
  sme_terceirizadas/pre_recebimento/migrations/0024_alter_imagemdotipodeembalagem_arquivo.py
  sme_terceirizadas/pre_recebimento/migrations/0025_alter_tipodeembalagemdelayout_status.py
  sme_terceirizadas/pre_recebimento/models/cronograma.py
Labels: feature

#3028 Feature/104604-CADASTROS-tela-nova-permissão-lançamentos-especiais-na-medição-inicial
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0026_alimentacaolancamentoespecial.py
  sme_terceirizadas/medicao_inicial/migrations/0027_auto_20231010_1420.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/urls.py
Labels: enhancement, feature

#3029 Hom - Atualizado em 10/10 as 16h55
  sme_terceirizadas/kit_lanche/migrations/0019_solicitacaokitlancheunificada_evento.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0026_alimentacaolancamentoespecial.py
  sme_terceirizadas/medicao_inicial/migrations/0027_auto_20231010_1420.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/urls.py
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cei.html
  sme_terceirizadas/relatorios/templates/bloco_kit_lanche_passeio_cemei.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_cemei.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_passeio.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_passeio_cei.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_unificado.html
Labels: enhancement, feature

#3043 Feature/104870 descricao evento especifico
  sme_terceirizadas/escola/__tests__/test_serializers.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/constants.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0037_diasmotivosinclusaodealimentacaocemei_descricao_evento.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/utils.py
Labels: feature

#3044 HOM - Atualizado 16/10 09:45h
  sme_terceirizadas/escola/__tests__/test_serializers.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/constants.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0037_diasmotivosinclusaodealimentacaocemei_descricao_evento.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
  sme_terceirizadas/relatorios/utils.py
Labels: feature

#3042 Feature/104622-CADASTROS-filtro-e-grid-resultados-permissão-lançamentos-especiais-na-medição-inicial
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0029_alter_permissaolancamentoespecial_options_and_more.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#3046 Hom - Atualizado em 16/10 as 11h35
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0029_alter_permissaolancamentoespecial_options_and_more.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#3045 Fix: usar filter para evitar erro 500
  sme_terceirizadas/paineis_consolidados/api/serializers.py
Labels: bug

#3047 Hom - Atualizado 16/10 às 11:30h
  sme_terceirizadas/paineis_consolidados/api/serializers.py
Labels: bug

#3052 Feature/104724-MI-ajustes-acompanhamento-lançamentos-usuário-medição-codae
  sme_terceirizadas/medicao_inicial/api/constants.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: enhancement, feature

#3053 Hom - Atualizado em 16/10 as 17h50
  sme_terceirizadas/medicao_inicial/api/constants.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: enhancement, feature

#3059 Hom - Atualizado em 17/10 às 12:20h
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cemei.html
  sme_terceirizadas/relatorios/templates/solicitacao_inclusao_alimentacao_cemei.html
Labels: bug

#3068 Feature/104716-MI-tooltip-sobremesa-doce-usuários-dre-e-medição-conferência-lançamentos
  sme_terceirizadas/medicao_inicial/validators.py
Labels: enhancement, feature

#3069 Hom - Atualizado em 19/10 as 10h10
  sme_terceirizadas/medicao_inicial/validators.py
Labels: enhancement

#3091 Feature: Alterar serializer para trazer informações mais completas
  sme_terceirizadas/medicao_inicial/api/serializers.py
Labels: feature

#3097 Feature/101694-MI-dre-salvamento-solicitação-correção-período-tela-conferência-lançamentos
  sme_terceirizadas/medicao_inicial/api/filters.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#3099 Hom - Atualizado em 25/10 as 15h35
  sme_terceirizadas/medicao_inicial/api/filters.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#3101 Feature: não permitir criar solicitações para mesmo tipo turma e mês
  sme_terceirizadas/dados_comuns/validators.py
Labels: feature

#3102 HOM - Atualizado em 26/10 às 11:00h
  sme_terceirizadas/conftest.py
  sme_terceirizadas/dados_comuns/validators.py
  sme_terceirizadas/pre_recebimento/__tests__/test_urls.py
  sme_terceirizadas/pre_recebimento/api/viewsets.py
Labels: feature

#3103 Feature/71080-MI-desmock-dados-tela-inicial-medição-escolas-cei
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: enhancement, feature

#3115 Feature/101001-MI-tela-detalhamento-períodos-devolvidos-para-ajustes-dre-escolas-cei
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#3116 Hom - Atualizado em 30/10 as 10h55
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#3117 Feature/106461-MI-envio-correção-para-dre-escolas-cei
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#3119 Hom - Atualizado em 30/10 as 15h20
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#3132 Hom - Atualizado em 31/10 as 12h25
  sme_terceirizadas/cardapio/__tests__/test_validators.py
  sme_terceirizadas/cardapio/api/serializers/serializers_create.py
  sme_terceirizadas/cardapio/api/validators.py
Labels: enhancement

#3128 Feature: Validar kit lanche e Lanche emergencial na medição inicial
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/validators.py
Labels: feature
