Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-04, with the labels that each got.

#2301 Feature/90051 disparo email questionamentos
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/codae_questiona_reclamacao.html
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#2305 Feature: links diferentes para reclamações de terceirizada, UE e Nutri
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: feature

#2306 Hom atualizado 06/04 as 13:40
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/codae_questiona_reclamacao.html
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#2307 Fix: correção na formatação do horário de questionamento
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: bug

#2309 Hom atualizado 06/04 as 16:20
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: bug

#2315 Feature: task para atualizar cache diariamente para consultar matriculados por faixa
  sme_terceirizadas/escola/management/commands/atualiza_cache_matriculados_por_faixa.py
  sme_terceirizadas/escola/tasks.py
Labels: feature

#2316 Hom - atualizado até 10/04 as 17h
  .dockerignore
  Dockerfile
  Jenkinsfile
  sme_terceirizadas/escola/management/commands/atualiza_cache_matriculados_por_faixa.py
  sme_terceirizadas/escola/tasks.py
Labels: feature

#2314 Feature/86236-MI-tela-lançamento-ETEC
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/api/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/utils.py
Labels: enhancement, feature

#2322 Hom Atualizado 10/04 as 19h05
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/api/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/utils.py
Labels: enhancement, feature

#2335 Feature/86236-MI-tela-lançamento-ETEC
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/utils.py
Labels: enhancement

#2336 Hom Atualizado 11/04 as 17h25
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/utils.py
  sme_terceirizadas/pre_recebimento/__tests__/test_urls.py
  sme_terceirizadas/pre_recebimento/api/serializers/serializers.py
  sme_terceirizadas/pre_recebimento/api/viewsets.py
  sme_terceirizadas/pre_recebimento/models/cronograma.py
Labels: enhancement

#2343 Feature/90028 relatorio alunos matriculados pdf
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/tasks.py
  sme_terceirizadas/relatorios/templates/cabecalho_rodape_relatorio_dietas_terceirizada.html
  sme_terceirizadas/relatorios/templates/relatorio_alunos_matriculados.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: feature

#2346 HOM - Atualizado até 13/04 09:30
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/tasks.py
  sme_terceirizadas/relatorios/templates/cabecalho_rodape_relatorio_dietas_terceirizada.html
  sme_terceirizadas/relatorios/templates/relatorio_alunos_matriculados.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: feature

#2349 Hom Atualizado 13/04 as 13h20
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: enhancement, feature

#2350 Feature/81324 relatorio medicao pagina 1
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0017_merge_20230413_0937.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/static/css/_variaveis.scss
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
Labels: feature

#2216 Feature/82642 analise viabilidade pdf medicao inicial
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dieta_especial/api/filters.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0014_auto_20230313_1231.py
  sme_terceirizadas/medicao_inicial/migrations/0017_merge_20230413_0937.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/static/css/_variaveis.scss
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: feature

#2351 Hom Atualizado 14/04 as 10h30
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dieta_especial/api/filters.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0014_auto_20230313_1231.py
  sme_terceirizadas/medicao_inicial/migrations/0017_merge_20230413_0937.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/static/css/_variaveis.scss
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: feature

#2354 Bugfix/81324 corrigir utils medicao
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2357 Bugfix/81324 corrigir viewset medicao
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2381 Feature/88612-MI-aprimoramento-regras-campos-de-programas-e-projetos
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
Labels: enhancement, feature

#2382 Hom Atualizado 24/04 as 11h05
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
Labels: enhancement, feature

#2392 Bugfix/92376/busca produtos dash
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#2405 Fix: corrigir a repetição do cabeçalho em casos de CEI ou CEMEI
  sme_terceirizadas/escola/utils_montar_planilha_matriculados.py
Labels: bug

#2406 HOM - Atualizado até 27/04 16:00
  sme_terceirizadas/escola/utils_montar_planilha_matriculados.py
Labels: bug

#2411 Fix: bordas das células mescladas
  sme_terceirizadas/escola/utils_montar_planilha_matriculados.py
Labels: bug

#2412 Hom atualizado 28/04 as 17h30
  sme_terceirizadas/escola/utils_montar_planilha_matriculados.py
Labels: bug

#2413 Feature: exibir alunos com solicitações de alteração UE na tela de kit lanche
  sme_terceirizadas/dieta_especial/api/viewsets.py
Labels: feature

#2414 HOM - Atualizado até 28/04 às 19h10
  sme_terceirizadas/dieta_especial/api/viewsets.py
Labels: feature
