Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-11, with the labels that each got.

#3137 Feature/103883 validacoes etec e programas projetos
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/validators.py
  sme_terceirizadas/paineis_consolidados/utils.py
Labels: feature

#3139 Feature/106422 alterar coluna tipo contagem
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0031_solicitacaomedicaoinicial_tipos_contagem_alimentacao.py
  sme_terceirizadas/medicao_inicial/migrations/0032_remove_solicitacaomedicaoinicial_tipo_contagem_alimentacoes_and_more.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/paineis_consolidados/__tests__/conftest.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
Labels: feature

#3140 HOM - Atualizado em 06/11 às 09:00h
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0031_solicitacaomedicaoinicial_tipos_contagem_alimentacao.py
  sme_terceirizadas/medicao_inicial/migrations/0032_remove_solicitacaomedicaoinicial_tipo_contagem_alimentacoes_and_more.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/paineis_consolidados/__tests__/conftest.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
Labels: feature

#3141 Feature: verificar se a chave tipos_contagem_alimentacao pertence a um FormData
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
Labels: bug

#3142 HOM - Atualizado 06/11 às 09:55h
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
Labels: bug

#3166 Feature/107598 pdf produtos suspensos por edital
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/tasks.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/produtos_terceirizada.scss
  sme_terceirizadas/relatorios/templates/produtos_suspensos_por_edital.html
Labels: feature

#3183 HOM - Atualizado em 16/11 às 08:50
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/tasks.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/produtos_terceirizada.scss
  sme_terceirizadas/relatorios/templates/produtos_suspensos_por_edital.html
Labels: feature

#3199 Feature/107018-MI-tela-lançamento-infantil-integral-manhã-tarde-escola-cemei
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0033_criar_grupos_medicao_infantil.py
Labels: enhancement, feature

#3202 Hom - Atualizado em 20/11 as 16h25
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0033_criar_grupos_medicao_infantil.py
Labels: enhancement, feature

#3218 Feature/108755-MI-registro-histórico-logs-dietas-autorizadas-escolas-cemei
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_utils.py
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/dieta_especial/migrations/0058_logquantidadedietasautorizadas_cei_ou_emei.py
  sme_terceirizadas/dieta_especial/models.py
  sme_terceirizadas/dieta_especial/tasks.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/constants.py
  sme_terceirizadas/escola/models.py
Labels: enhancement, feature

#3219 Hom - Atualizado em 24/11 as 19h30
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_utils.py
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/dieta_especial/migrations/0058_logquantidadedietasautorizadas_cei_ou_emei.py
  sme_terceirizadas/dieta_especial/models.py
  sme_terceirizadas/dieta_especial/tasks.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/constants.py
  sme_terceirizadas/escola/models.py
Labels: enhancement, feature

#3232 Feature/108741 mi correcao ciencia dre
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_models.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0034_solicitacaomedicaoinicial_dre_ciencia_correcao_data_and_more.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/relatorios/relatorios.py
Labels: feature

#3239 Feature/107026-MI-tela-lançamento-infantil-dietas-escolas-cemei
  sme_terceirizadas/dieta_especial/api/filters.py
Labels: feature

#3244 Hom - Atualizado em 29/11 as 17h30
  sme_terceirizadas/dieta_especial/api/filters.py
Labels: feature
