Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-08, with the labels that each got.

#2759 Feature/100127-MI-registro-do-histórico-de-matrículas-por-dia-e-faixa-etária-escolas-cei-ceiceu-cci
  sme_terceirizadas/escola/__tests__/conftest.py
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/__tests__/test_urls.py
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/api/filters.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/management/commands/atualiza_cache_matriculados_por_faixa.py
  sme_terceirizadas/escola/migrations/0058_logalunosmatriculadosfaixaetariadia.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/urls.py
Labels: enhancement, feature

#2760 Hom Atualizado 08/08 as 10h30
  sme_terceirizadas/escola/__tests__/conftest.py
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/__tests__/test_urls.py
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/api/filters.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/management/commands/atualiza_cache_matriculados_por_faixa.py
  sme_terceirizadas/escola/migrations/0058_logalunosmatriculadosfaixaetariadia.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/urls.py
Labels: enhancement, feature

#2774 Feature/98616 fluxo suspender apos alteracao
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/migrations/0080_alter_datahoravinculoprodutoedital_produto_edital.py
  sme_terceirizadas/produto/models.py
Labels: feature

#2776 Feature/98617 fluxo vincular produto editais
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
Labels: feature

#2785 Feature/71446-MI-tela-lançamento-integral-alimentação-escolas-cei-ceiceu-cci
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0023_valormedicao_faixa_etaria.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#2788 Hom Atualizado 11/08 as 17h20
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0023_valormedicao_faixa_etaria.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#2816 Feature/94889 criar historico correcoes periodo escolar
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0024_auto_20230817_1916.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: feature

#2824 Fix: deve criar log dos dados alterados ao atualiza ValorMedicao
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2826 HOM - Atualizado em 21/08 às 11:20h
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: feature

#2817 Feature/100200-MI-registro-histórico-dietas-especiais-por-dia-faixa-etária-e-período-escolas-cei
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_utils.py
  sme_terceirizadas/dieta_especial/migrations/0055_logquantidadedietasautorizadascei.py
  sme_terceirizadas/dieta_especial/models.py
  sme_terceirizadas/dieta_especial/tasks.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: enhancement, feature

#2830 Hom Atualizado 22/08 as 12h20
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_utils.py
  sme_terceirizadas/dieta_especial/migrations/0055_logquantidadedietasautorizadascei.py
  sme_terceirizadas/dieta_especial/models.py
  sme_terceirizadas/dieta_especial/tasks.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: enhancement, feature

#2833 Bugfix/101323 corrigir metodo deletar logs
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2847 Hom - Atualizado em 25/08 às 10:30h
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2846 Feature/71614-MI-tela-lançamento-integral-dieta-especial-escolas-cei
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/dieta_especial/api/filters.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/urls.py
Labels: enhancement, feature

#2848 Hom - Atualizado em 25/08 as 11h10
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/dieta_especial/api/filters.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/urls.py
Labels: enhancement, feature

#2854 Feature/71444-MI-tela-lançamento-parcial-alimentação-escolas-cei
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/escola/__tests__/conftest.py
  sme_terceirizadas/escola/__tests__/test_models.py
Labels: enhancement, feature

#2855 Hom - Atualizado em 28/08 as 18h00
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/escola/__tests__/conftest.py
  sme_terceirizadas/escola/__tests__/test_models.py
Labels: enhancement, feature

#2861 Fix/102403-GA-erro-ao-cancelar-solicitação-lanche-emergencial
  sme_terceirizadas/escola/tasks.py
Labels: bug

#2862 Hom - Atualizado em 29/08 as 20h15
  sme_terceirizadas/escola/tasks.py
Labels: bug

#2865 HOM - Atualizado em 29/08 às 22:45
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2867 HOM - Atualizado em 30/08 às 12:00h
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: bug

#2869 Feature/103027-MI-exclusão-alunos-parciais-que-não-estão-mais-matriculados-escolas-cei
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/utils.py
Labels: enhancement

#2872 Hom - Atualizado em 31/08 as 15h10
  sme_terceirizadas/escola/utils.py
Labels: enhancement
