Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-01, with the labels that each got.

#1953 Hotfix/83193-PeD-ajuste-modal-vincular-produtos-aos-editais
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1954 Hotfix/83192-GA-ajuste-card-aguardando-retorno-codae
  sme_terceirizadas/paineis_consolidados/models.py
Labels: bug

#1955 Prod Atualizado 04/01 as 11h50
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1956 Hom Atualizado 04/01 as 12h00
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug

#1963 Feature/74279-MI-alterações-área-inf-básicas-medição-inicial
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0006_auto_20230106_1138.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/tasks.py
Labels: enhancement, feature

#1965 Hom Atualizado 06/01 as 17h30
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0006_auto_20230106_1138.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/tasks.py
Labels: enhancement, feature

#1966 Feature/76113-DI-melhoria-para-deletar-objetos-SolicitacaoAberta-caso-necessário
  config/settings/base.py
  sme_terceirizadas/dados_comuns/api/serializers.py
  sme_terceirizadas/dados_comuns/migrations/0066_solicitacaoaberta_datetime_ultimo_acesso.py
  sme_terceirizadas/dados_comuns/models.py
  sme_terceirizadas/dados_comuns/tasks.py
Labels: enhancement, feature

#1971 Feature/82438 filtros lotes dres para codae
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
Labels: feature

#1975 Feature/81647 dias motivos inclusoes cei para pdf
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/novo_solicitacao_inclusao_alimentacao_cei.html
Labels: feature

#1976 Hom atualizado 10/01 as 11h05
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/novo_solicitacao_inclusao_alimentacao_cei.html
Labels: feature

#1983 Feature: corrigir datas da inclusao de alimentação CEI no pdf e no serializer
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/models.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/relatorios/templates/bloco_inclusao_cei.html
Labels: feature

#1987 Fix: return 0 quando valor for nulo
  sme_terceirizadas/inclusao_alimentacao/models.py
Labels: bug

#1992 Feature/75580 medicao inicial ordenacao alimentacoes
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/migrations/0042_auto_20230112_1501.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/escola/models.py
Labels: feature

#1993 HOM - Atualizada até 13/01 às 11:00
  sme_terceirizadas/cardapio/__tests__/conftest.py
  sme_terceirizadas/cardapio/__tests__/test_urls.py
  sme_terceirizadas/cardapio/migrations/0042_auto_20230112_1501.py
  sme_terceirizadas/cardapio/models.py
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/escola/models.py
Labels: feature

#1997 Feature/71893-MI-integração-com-gestão-alimentacao-inclusão
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/paineis_consolidados/api/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: enhancement, feature

#1998 Hom Atualizado 16/01 as 10h40
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/paineis_consolidados/api/constants.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/relatorios/constants.py
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_unificado.html
Labels: enhancement, feature

#2001 Fix: requisições devem passar apenas uma dre e um lote ao filtrar solicitações
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
Labels: bug

#2002 Hom atualizado 17/01 as 11h00
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
Labels: bug

#2022 Feature/83905-GA-Escola-cancelar-solicitação-kit-lanche-unificado
  sme_terceirizadas/dados_comuns/behaviors.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/inclusao_alimentacao/migrations/0032_auto_20230120_1711.py
  sme_terceirizadas/kit_lanche/__tests__/conftest.py
  sme_terceirizadas/kit_lanche/__tests__/test_models.py
  sme_terceirizadas/kit_lanche/__tests__/test_urls.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/kit_lanche/migrations/0017_auto_20230120_1711.py
  sme_terceirizadas/kit_lanche/models.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_historico_questionamento.html
  sme_terceirizadas/relatorios/templates/bloco_observacoes.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_unificado.html
Labels: enhancement, feature

#2024 Feature/83905-GA-Escola-cancelar-solicitação-kit-lanche-unificado
  sme_terceirizadas/relatorios/relatorios.py
Labels: enhancement, feature

#2025 Hom Atualizado 24/01 as 18h15
  sme_terceirizadas/relatorios/relatorios.py
Labels: enhancement, feature

#2003 Feature/82445 ga solicitacoes similares kit lanche
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/models.py
Labels: feature

#2029 HOM - Atualizado até 26/01
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/models.py
Labels: feature

#2042 Feature/82443 filtro lote para dashboard dre
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: feature

#2044 Hom - Atualizado até 27/01 as 12:00
  sme_terceirizadas/cardapio/api/viewsets.py
  sme_terceirizadas/inclusao_alimentacao/api/viewsets.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
Labels: feature

#2041 Feature/83976-GA-DRE-cancelar-solicitação-kit-lanche-unificado
  sme_terceirizadas/kit_lanche/__tests__/conftest.py
  sme_terceirizadas/kit_lanche/__tests__/test_urls.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/kit_lanche/utils.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_fluxo_de_status.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_unificado.html
  sme_terceirizadas/relatorios/utils.py
Labels: enhancement, feature

#2045 Hom Atualizado 27/01 as 13h40
  sme_terceirizadas/kit_lanche/__tests__/conftest.py
  sme_terceirizadas/kit_lanche/__tests__/test_urls.py
  sme_terceirizadas/kit_lanche/api/serializers/serializers.py
  sme_terceirizadas/kit_lanche/api/viewsets.py
  sme_terceirizadas/kit_lanche/utils.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_fluxo_de_status.html
  sme_terceirizadas/relatorios/templates/solicitacao_kit_lanche_unificado.html
  sme_terceirizadas/relatorios/utils.py
Labels: enhancement, feature

#2050 Feature/72324-MI-permissionamento-para-finalizar-medição-inicial
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
Labels: enhancement, feature

#2048 Feature: remover código estático que impedia de exibir os questionamentos e respostas em GA
  sme_terceirizadas/relatorios/utils.py
Labels: feature

#2052 Hom Atualizado 30/01 as 12h53
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/fixtures/categorias_de_medicao.yaml
  sme_terceirizadas/medicao_inicial/fixtures/tipos_de_contagem.yaml
  sme_terceirizadas/medicao_inicial/migrations/0007_auto_20230120_1706.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/relatorios/utils.py
Labels: feature

#2057 Feature/85122-débito-técnico-upgrade-libs-flower-n-django-debug-toolbar
  Pipfile
  Pipfile.lock
Labels: enhancement

#2059 Fix: ícone do fluxo de status
  sme_terceirizadas/relatorios/__tests__/test_templatetags.py
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: bug

#2060 Hom atualizado 30/01 as 18h30
  sme_terceirizadas/relatorios/__tests__/test_templatetags.py
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: bug

#2061 Feature: DT Log da task de atualizar alunos matriculados
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/escola/migrations/0056_logatualizadadosaluno.py
  sme_terceirizadas/escola/models.py
Labels: feature

#2062 Feature: DT Log da task de atualizar alunos matriculados
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
  sme_terceirizadas/escola/migrations/0056_logatualizadadosaluno.py
  sme_terceirizadas/escola/models.py
Labels: feature
