Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2023-05, with the labels that each got.

#2415 Feature: comando para relacionar protocolos a dietas
  sme_terceirizadas/dieta_especial/management/commands/processar_planilha_retorno_nucleo.py
Labels: feature

#2417 Feature/81331-MI-relatório-medição-inicial-ue-tabelas-alimentação-dietas
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#2418 Hom Atualizado 02/05 as 15h45
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#2419 Feature/81331-MI-relatório-medição-inicial-ue-tabelas-alimentação-dietas
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: enhancement, feature

#2420 Hom Atualizado 03/05 as 09h10
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/utils.py
Labels: enhancement, feature

#2421 Prod Atualizado 03/05 as 14h00
  Pipfile
  Pipfile.lock
  sme_terceirizadas/conftest.py
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/filters.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/management/commands/processar_planilha_retorno_nucleo.py
  sme_terceirizadas/dieta_especial/tasks.py
  sme_terceirizadas/escola/__tests__/conftest.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/tasks.py
  sme_terceirizadas/escola/utils_montar_planilha_matriculados.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/perfil/__tests__/conftest.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
  sme_terceirizadas/perfil/api/serializers.py
  sme_terceirizadas/perfil/api/viewsets.py
  sme_terceirizadas/perfil/models/perfil.py
  sme_terceirizadas/pre_recebimento/__tests__/test_urls.py
  sme_terceirizadas/pre_recebimento/migrations/0010_auto_20230427_1014.py
  sme_terceirizadas/pre_recebimento/models/cronograma.py
  sme_terceirizadas/pre_recebimento/utils.py
  sme_terceirizadas/processamento_arquivos/dieta_especial/importa_dietas_especiais.py
  sme_terceirizadas/produto/__tests__/conftest.py
  sme_terceirizadas/produto/__tests__/test_urls.py
  sme_terceirizadas/produto/api/filters.py
  sme_terceirizadas/produto/api/serializers/serializers.py
  sme_terceirizadas/produto/api/serializers/serializers_create.py
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/relatorios/__tests__/test_relatorios.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: feature

#2425 Hotfix/93542-DE-aprimoramento-conteúdo-impressão-relatório-dieta-especial
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
Labels: enhancement

#2426 Prod atualizado 05/05 as 14h25
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
Labels: enhancement

#2427 Hom atualizado 05/05 as 14h30
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
Labels: enhancement

#2428 Dev atualizado 05/05 as 15:50
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
Labels: enhancement

#2423 Feature/85831-MI-relatorio-medição-inicial-ue-observações-diárias-lançamento
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#2431 Hom Atualizado 08/05 as 18h25
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#2438 Feature/90035-MI-relatório-pdf-medição-inicial-tabela-de-somatórios
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
Labels: enhancement, feature

#2441 Hom Atualizado 11/05 as 17h20
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/pre_recebimento/__tests__/test_urls.py
  sme_terceirizadas/pre_recebimento/api/viewsets.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/pre_recebimento/cronogramas/cronograma.html
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
Labels: enhancement, feature

#2442 Feature/91721 salvar correcao ocorrencia
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0018_auto_20230512_0413.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/urls.py
Labels: feature

#2455 HOM - Atualizado até 15/05 15:50
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/pre_recebimento_notificacao_solicitacao_cronograma_ciente.html
  sme_terceirizadas/dados_comuns/templates/pre_recebimento_notificacao_solicitacao_parecer_dinutre.html
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0018_auto_20230512_0413.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/urls.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: feature

#2456 Fix: Exibir justificativas de cancelamento quando necessário. Fluxo de status termina com CODAE
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: bug

#2457 HOM - Atualizado até 15/05 18:00
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: bug

#2458 Feature/91725-MI-aprimoramento-tela-acompanhamento-e-status-das-medições-dre-codae
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#2459 Hom Atualizado 15/05 as 19h35
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#2461 Fix: pode retornar mais de um log de atualização da quantidade de alunos matriculados por período e tipo de turma
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2463 HOM - Atualizada até 16/05 às 11:30
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2464 Fix/PeD-ajuste-dashboard-card-homologados
  sme_terceirizadas/produto/api/viewsets.py
Labels: bug, enhancement

#2466 Feature: retornar alunos maiores que 6 anos no contador da faixa de até 6 anos nas solicitações de kit lanche
  sme_terceirizadas/escola/models.py
Labels: feature

#2468 Hom Atualizado 16/05 as 16h20
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/escola/models.py
Labels: feature

#2473 Feature/92083-MI-aprimoramento-tela-acompanhamento-e-status-das-medições-escola
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2474 Hom Atualizado 15/05 as 20h50
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2475 Fix: testes, bloco para calcular quantidades por faixa
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/__tests__/test_urls.py
  sme_terceirizadas/escola/models.py
Labels: bug

#2476 Hom Atualizado 16/05 as 21h30
  sme_terceirizadas/escola/__tests__/test_models.py
  sme_terceirizadas/escola/__tests__/test_urls.py
  sme_terceirizadas/escola/models.py
Labels: bug

#2479 Fix: append lista
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2480 Hom Atualizado 17/05 as 14:05
  sme_terceirizadas/medicao_inicial/utils.py
Labels: bug

#2487 Feature/91846 aprovacao formulario ocorrencias
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: feature

#2488 HOM - Atualizado até 19/05 14h20
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: feature

#2486 Feature/93523-MI-exportar-pdf-medição-inicial-pela-central-de-downloads
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/tasks.py
  sme_terceirizadas/relatorios/relatorios.py
Labels: enhancement, feature

#2492 Hotfix/94054-DE-consulta-dieta-do-aluno-com-resultado-errado
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#2493 Prod atualizado 22/05 as 19h00
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#2494 Hom atualizado 22/05 as 19h05
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#2495 Dev atualizado 22/05 as 19h05
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/dieta_especial/utils.py
Labels: bug

#2498 Hom atualizado 23/05 as 11h45
  sme_terceirizadas/dados_comuns/fluxo_status.py
Labels: bug

#2501 Fix: criar endpoint para consultar somatório de matriculados por faixa dos alunos CEI
  sme_terceirizadas/escola/api/viewsets.py
Labels: bug

#2502 Fix: criar endpoint para consultar somatório de matriculados por faixa dos alunos CEI
  sme_terceirizadas/escola/api/viewsets.py
Labels: bug

#2503 Merge pull request #2501 from prefeiturasp/hotfix/numero-alunos-cei-kit-lanche
  sme_terceirizadas/escola/api/viewsets.py
Labels: bug

#2504 Merge pull request #2501 from prefeiturasp/hotfix/numero-alunos-cei-kit-lanche
  sme_terceirizadas/escola/api/viewsets.py
Labels: bug

#2509 Feature/91845-MI-envio-da-aprovação-medição-inicial-pela-dre
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2516 Hom Atualizado 25/05 as 15h40
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement, feature

#2517 Feature/91848-MI-envio-de-email-para-ue-sobre-aprovação-da-medição-pela-dre
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/medicao_dre_aprova_solicitacao.html
Labels: enhancement, feature

#2518 Hom Atualizado 26/05 as 09h57
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/medicao_dre_aprova_solicitacao.html
Labels: enhancement, feature

#2519 Feature: logica de deletar logs
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: feature

#2520 Feature/92884-MI-página-inicial-aprovado-pela-dre
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#2521 Hom Atualizado 26/05 as 21h00
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement

#2523 Feature: disparar e-mail para escola ao solicitar correção da medição
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/medicao_dre_solicita_correcao.html
Labels: feature

#2522 Feature: endpoint para enviar solicitação de medição para correção
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/medicao_dre_solicita_correcao.html
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: feature

#2526 HOM - Atualizado em 30/05/2023 12:45h
  sme_terceirizadas/dados_comuns/fluxo_status.py
  sme_terceirizadas/dados_comuns/templates/medicao_dre_solicita_correcao.html
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: feature

#2527 Fix: texto do link para acessar sistema.
  sme_terceirizadas/dados_comuns/templates/medicao_dre_solicita_correcao.html
Labels: bug
