Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2024-02, with the labels that each got.

#3509 Feature/103253-MI-tela-lançamento-manhã-tarde-escola-emebs
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0035_valormedicao_infantil_ou_fundamental.py
  sme_terceirizadas/medicao_inicial/migrations/0036_merge_20240206_2011.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
Labels: enhancement, feature

#3516 Hom - Atualizado em 07/02 as 23h35
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/admin.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/migrations/0035_valormedicao_infantil_ou_fundamental.py
  sme_terceirizadas/medicao_inicial/migrations/0036_merge_20240206_2011.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/perfil/__tests__/test_urls.py
Labels: enhancement, feature

#3525 PROD: atualizado em 09/02/2024 as 12:40
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/perfil/models/usuario.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: enhancement, feature

#3528 DEV: atualizado em 09/01/2024 as 14:50 (descendo)
  sme_terceirizadas/dados_comuns/constants.py
  sme_terceirizadas/dados_comuns/permissions.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/perfil/models/usuario.py
  sme_terceirizadas/produto/api/viewsets.py
Labels: enhancement, feature

#3531 Feature/113223-MI-log-alunos-quantidade-dietas-escolas-emebs
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/dieta_especial/constants.py
  sme_terceirizadas/dieta_especial/migrations/0059_logquantidadedietasautorizadas_infantil_ou_fundamental.py
  sme_terceirizadas/dieta_especial/models.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/constants.py
Labels: enhancement, feature

#3540 Hom - Atualizado em 12/02 as 18h
  sme_terceirizadas/dados_comuns/utils.py
  sme_terceirizadas/dieta_especial/admin.py
  sme_terceirizadas/dieta_especial/constants.py
  sme_terceirizadas/dieta_especial/migrations/0059_logquantidadedietasautorizadas_infantil_ou_fundamental.py
  sme_terceirizadas/dieta_especial/models.py
  sme_terceirizadas/dieta_especial/utils.py
  sme_terceirizadas/escola/constants.py
Labels: enhancement, feature

#3556 Hom - Atualizado em 15/02 as 10h
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_utils.py
Labels: enhancement, feature

#3576 Feature/114379-MI-relatório-medição-inicial-somatório-dietas-especiais-escolas-emef-emei
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/medicao_inicial/validators.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
Labels: enhancement, feature

#3577 Hom - Atualizado em 21/02 as 10h05m
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_utils.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/medicao_inicial/validators.py
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/static/css/relatorio_solicitacao_medicao_por_escola.scss
  sme_terceirizadas/relatorios/templates/relatorio_solicitacao_medicao_por_escola.html
Labels: enhancement, feature

#3578 Feature/114379-MI-relatório-medição-inicial-somatório-dietas-especiais-escolas-emef-emei
  sme_terceirizadas/medicao_inicial/utils.py
Labels: enhancement

#3580 Hom - Atualizado em 21/02 as 17h25m
  sme_terceirizadas/medicao_inicial/utils.py
Labels: enhancement

#3586 Feature/113228-MI-tela-conferência-lançamentos-dre-medição-escolas-emebs
  sme_terceirizadas/medicao_inicial/api/serializers.py
Labels: enhancement

#3587 Hom - Atualizado em 23/02 as 09h55
  sme_terceirizadas/medicao_inicial/api/serializers.py
Labels: enhancement

#3590 Feature/114735 justificativa exclusao edital
  sme_terceirizadas/produto/api/viewsets.py
  sme_terceirizadas/produto/models.py
Labels: feature

#3598 Feature/114982-MI-salvamento-solicitação-correção-períodos-enviados-escolas-emebs
  sme_terceirizadas/medicao_inicial/__tests__/test_models.py
  sme_terceirizadas/medicao_inicial/migrations/0037_diaparacorrigir_infantil_ou_fundamental.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#3599 Hom - Atualizado em 26/02 as 18h32
  sme_terceirizadas/medicao_inicial/__tests__/test_models.py
  sme_terceirizadas/medicao_inicial/migrations/0037_diaparacorrigir_infantil_ou_fundamental.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#3600 Feature/114735 justificativa exclusao edital pt2
  sme_terceirizadas/cardapio/api/serializers/serializers.py
  sme_terceirizadas/inclusao_alimentacao/api/serializers/serializers.py
  sme_terceirizadas/produto/models.py
Labels: bug

#3604 Hom - Atualizado em 27/02 as 12h45
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement
