Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2024-03, with the labels that each got.

#3621 Feature/113303-MI-botão-finalizar-escolas-emebs-períodos-manhã-tarde-comuns
  sme_terceirizadas/dados_comuns/migrations/0114_alter_logsolicitacoesusuario_solicitacao_tipo.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/data/mock_tabelas_relatorio_medicao_emebs.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/__tests__/test_validators.py
  sme_terceirizadas/medicao_inicial/api/constants.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/validators.py
Labels: enhancement, feature

#3625 Hom - Atualizado em 01/03 as 13h45
  sme_terceirizadas/dados_comuns/migrations/0114_alter_logsolicitacoesusuario_solicitacao_tipo.py
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/data/mock_tabelas_relatorio_medicao_emebs.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/__tests__/test_validators.py
  sme_terceirizadas/medicao_inicial/api/constants.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/validators.py
Labels: enhancement, feature

#3632 Feature/113303-MI-botão-finalizar-escolas-emebs-períodos-manhã-tarde-comuns-pt2
  sme_terceirizadas/medicao_inicial/__tests__/test_validators.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/validators.py
Labels: enhancement, feature

#3633 Hom - Atualizado em 01/03 as 17h45
  sme_terceirizadas/medicao_inicial/__tests__/test_validators.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/validators.py
Labels: enhancement, feature

#3634 Feature/113229-validação-programas-projetos-emebs
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/validators.py
Labels: enhancement, feature

#3637 Hom - Atualizado em 01/03 as 20h
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/models.py
  sme_terceirizadas/medicao_inicial/validators.py
Labels: enhancement, feature

#3654 Hotfix/117125-DE-dietas-negadas-retirar-dados-nutri
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_fluxo_status_homologacao.html
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#3656 PROD: atualizado em 07/03/2024 as 17:30
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_fluxo_status_homologacao.html
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#3657 HOM: atualizado em 07/03/2024 as 17:30 (descendo)
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_fluxo_status_homologacao.html
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#3660 DEV: atualizado em 08/03/2024 as 10:05 (descendo)
  sme_terceirizadas/relatorios/relatorios.py
  sme_terceirizadas/relatorios/templates/bloco_fluxo_status_homologacao.html
  sme_terceirizadas/relatorios/templates/solicitacao_dieta_especial.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#3667 Hom - Atualizado em 01/03 as 11:15
  sme_terceirizadas/escola/management/commands/atualiza_alunos_escolas.py
Labels: enhancement

#3671 Feature/115754 relatorio solicitacoes alimentacao totalizadores
  sme_terceirizadas/paineis_consolidados/__tests__/conftest.py
  sme_terceirizadas/paineis_consolidados/__tests__/test_url.py
  sme_terceirizadas/paineis_consolidados/api/serializers.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/utils/__init__.py
  sme_terceirizadas/paineis_consolidados/utils/totalizadores_relatorio_ga.py
  sme_terceirizadas/paineis_consolidados/utils/utils.py
Labels: feature

#3678 Feature/101650-MI-relatório-de-adesão-ue
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement

#3681 Hom - Atualizado em 13/03 as 10:50
  sme_terceirizadas/medicao_inicial/api/viewsets.py
Labels: enhancement
