Repository prefeiturasp/SME-Terceirizadas, pull requests merged in 2024-04, with the labels that each got.

#3742 Feature/117235-MI-pdf-relatório-controle-frequências-unidades-cei
  sme_terceirizadas/escola/admin.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/management/commands/atualiza_cache_matriculados_por_faixa.py
  sme_terceirizadas/escola/migrations/0069_logalunopordia.py
  sme_terceirizadas/escola/models.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/medicao_inicial/services/relatorio_controle_frequencia_pdf.py
  sme_terceirizadas/medicao_inicial/tasks.py
  sme_terceirizadas/medicao_inicial/utils.py
  sme_terceirizadas/relatorios/static/css/cabecalho_relatorio_controle_frequencia.scss
  sme_terceirizadas/relatorios/static/css/relatorio_controle_frequencia.scss
  sme_terceirizadas/relatorios/templates/cabecalho_relatorio_controle_frequencia.html
  sme_terceirizadas/relatorios/templates/relatorio_controle_frequencia.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#3760 Feature/117873-MI-pdf-relatório-controle-frequências-dietas-especiais-unidades-cei
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/medicao_inicial/services/relatorio_controle_frequencia_pdf.py
  sme_terceirizadas/pre_recebimento/migrations/0056_merge_20240402_1810.py
  sme_terceirizadas/relatorios/static/css/relatorio_controle_frequencia.scss
  sme_terceirizadas/relatorios/static/images/icone_tooltip_pb.png
  sme_terceirizadas/relatorios/templates/relatorio_controle_frequencia.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#3761 Hom - Atualizado em 02/04 as 18:43
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/medicao_inicial/services/relatorio_controle_frequencia_pdf.py
  sme_terceirizadas/pre_recebimento/migrations/0056_merge_20240402_1810.py
  sme_terceirizadas/relatorios/static/css/relatorio_controle_frequencia.scss
  sme_terceirizadas/relatorios/static/images/icone_tooltip_pb.png
  sme_terceirizadas/relatorios/templates/relatorio_controle_frequencia.html
  sme_terceirizadas/relatorios/templatetags/index.py
Labels: enhancement, feature

#3766 Fix/119138-MI-erro-ao-finalizar-medição-emef-cei
  sme_terceirizadas/medicao_inicial/validators.py
Labels: bug, enhancement

#3767 Hom - Atualizado em 04/04 as 10:25
  sme_terceirizadas/medicao_inicial/validators.py
Labels: bug, enhancement

#3774 Hotfix/119138-MI-erro-ao-finalizar-medição-programas-e-projetos
  sme_terceirizadas/medicao_inicial/validators.py
Labels: bug, enhancement

#3778 DEV: atualizado em 05/04/2024 as 11:40 (descendo)
  sme_terceirizadas/medicao_inicial/validators.py
Labels: bug, enhancement

#3779 Hotfix/119179-MI-relatório-controle-frequência-log-alunos-cei-passado-futuro
  setup.cfg
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/management/commands/cria_logs_alunos_por_dia_escolas_cei.py
  sme_terceirizadas/escola/tasks.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/medicao_inicial/services/relatorio_controle_frequencia_pdf.py
Labels: enhancement, feature

#3780 PROD: atualizado em 09/04/2024 as 10:35
  setup.cfg
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/management/commands/cria_logs_alunos_por_dia_escolas_cei.py
  sme_terceirizadas/escola/tasks.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/medicao_inicial/services/relatorio_controle_frequencia_pdf.py
Labels: enhancement, feature

#3781 HOM: atualizado em 09/04/2024 as 12:25 (descendo)
  setup.cfg
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/escola/management/commands/cria_logs_alunos_por_dia_escolas_cei.py
  sme_terceirizadas/escola/tasks.py
  sme_terceirizadas/escola/utils.py
  sme_terceirizadas/medicao_inicial/services/relatorio_controle_frequencia_pdf.py
Labels: enhancement, feature

#3791 Feature/118769-DE-relatório-dietas-autorizadas-filtros-e-grid
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/filters.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0041_alter_parametrizacaofinanceira_options.py
Labels: enhancement, feature

#3792 Hom - Atualizado em 12/04 as 10:30
  sme_terceirizadas/dieta_especial/__tests__/conftest.py
  sme_terceirizadas/dieta_especial/__tests__/test_urls.py
  sme_terceirizadas/dieta_especial/api/filters.py
  sme_terceirizadas/dieta_especial/api/serializers.py
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/escola/api/viewsets.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/migrations/0041_alter_parametrizacaofinanceira_options.py
Labels: enhancement, feature

#3795 Feature/111233 imr parametrizacao ocorrencias
  sme_terceirizadas/imr/admin.py
  sme_terceirizadas/imr/fixtures/tipo_pergunta.yaml
  sme_terceirizadas/imr/fixtures/tipo_resposta_modelo.yaml
  sme_terceirizadas/imr/migrations/0004_parametrizacaoocorrencia_tiporespostamodelo_and_more.py
  sme_terceirizadas/imr/models.py
Labels: feature

#3811 Feature/118803-DE-relatório-dietas-autorizadas-cards-quantidade
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/paineis_consolidados/__tests__/test_url.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/migrations/0038_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/migrations/0039_solicitacoes .py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/sql/0039_solicitacoes.sql
  sme_terceirizadas/paineis_consolidados/sql/0040_solicitacoes.sql
  sme_terceirizadas/paineis_consolidados/utils/datasets_graficos_relatorio_ga.py
  sme_terceirizadas/paineis_consolidados/utils/totalizadores_relatorio.py
  sme_terceirizadas/paineis_consolidados/utils/totalizadores_relatorio_ga.py
Labels: enhancement, feature

#3812 Hom - Atualizado em 18/04 as 10h
  sme_terceirizadas/dieta_especial/api/viewsets.py
  sme_terceirizadas/escola/api/serializers.py
  sme_terceirizadas/paineis_consolidados/__tests__/test_url.py
  sme_terceirizadas/paineis_consolidados/api/viewsets.py
  sme_terceirizadas/paineis_consolidados/migrations/0038_solicitacoes.py
  sme_terceirizadas/paineis_consolidados/migrations/0039_solicitacoes .py
  sme_terceirizadas/paineis_consolidados/models.py
  sme_terceirizadas/paineis_consolidados/sql/0039_solicitacoes.sql
  sme_terceirizadas/paineis_consolidados/sql/0040_solicitacoes.sql
  sme_terceirizadas/paineis_consolidados/utils/datasets_graficos_relatorio_ga.py
  sme_terceirizadas/paineis_consolidados/utils/totalizadores_relatorio.py
  sme_terceirizadas/paineis_consolidados/utils/totalizadores_relatorio_ga.py
Labels: enhancement, feature

#3813 Feature/118803-DE-relatório-dietas-autorizadas-cards-quantidade
  sme_terceirizadas/paineis_consolidados/utils/totalizadores_relatorio.py
Labels: enhancement, feature

#3816 Hom - Atualizado em 18/04 as 11:35
  sme_terceirizadas/paineis_consolidados/utils/totalizadores_relatorio.py
Labels: enhancement, feature

#3820 Feature/119535 imr tabela percentual descontos
  sme_terceirizadas/conftest.py
  sme_terceirizadas/imr/__tests__/test_models.py
  sme_terceirizadas/imr/admin.py
  sme_terceirizadas/imr/fixtures/factories/imr_base_factory.py
  sme_terceirizadas/imr/fixtures/faixa_pontuacao_imr.yaml
  sme_terceirizadas/imr/migrations/0007_faixapontuacaoimr.py
  sme_terceirizadas/imr/models.py
Labels: feature

#3822 Feature/120169 cadastro categorias ocorrencias
  sme_terceirizadas/imr/admin.py
  sme_terceirizadas/imr/fixtures/categoria_ocorrencia.yaml
Labels: feature

#3840 Hom - Atualizado em 26/04 as 09:20
  setup.cfg
  sme_terceirizadas/medicao_inicial/__tests__/conftest.py
  sme_terceirizadas/medicao_inicial/__tests__/test_models.py
  sme_terceirizadas/medicao_inicial/__tests__/test_urls.py
  sme_terceirizadas/medicao_inicial/api/serializers.py
  sme_terceirizadas/medicao_inicial/api/serializers_create.py
  sme_terceirizadas/medicao_inicial/api/viewsets.py
  sme_terceirizadas/medicao_inicial/management/commands/__init__.py
  sme_terceirizadas/medicao_inicial/management/commands/vincula_editais_e_dias_sobremesa_doce.py
  sme_terceirizadas/medicao_inicial/migrations/0043_alter_diasobremesadoce_unique_together_and_more.py
  sme_terceirizadas/medicao_inicial/models.py
Labels: enhancement, feature

#3838 Feature/119015 carga tipo ocorrencia imr
  sme_terceirizadas/conftest.py
  sme_terceirizadas/dados_comuns/helper_planilha_modelo.py
  sme_terceirizadas/imr/__tests__/test_services.py
  sme_terceirizadas/imr/admin.py
  sme_terceirizadas/imr/api/services.py
  sme_terceirizadas/imr/migrations/0010_importacaoplanilhatipoocorrencia_and_more.py
  sme_terceirizadas/imr/models.py
  sme_terceirizadas/templates/admin/imr/importacao_tipos_ocorrencia.html
  utility/carga_dados/imr/importa_dados.py
  utility/carga_dados/imr/schemas.py
  utility/carga_dados/processador_planilha_generico/models.py
Labels: feature

#3843 Feature/119255-CADASTROS-editais-e-contratos-add-campo-IMR
  sme_terceirizadas/terceirizada/migrations/0020_edital_eh_imr.py
  sme_terceirizadas/terceirizada/models.py
Labels: enhancement, feature
